import type {
  AttackDefinition,
  CreatureDefinition,
  Element,
  EnergyPool,
  RegionDefinition,
} from "./types";

export const ELEMENT_META: Record<
  Element,
  { name: string; short: string; color: string; glow: string; artSlot: 0 | 1 | 2 | 3 | 4 | 5 | 6 }
> = {
  fire: {
    name: "Fogo",
    short: "FO",
    color: "#ff7548",
    glow: "rgba(255, 117, 72, .38)",
    artSlot: 0,
  },
  water: {
    name: "Água",
    short: "AG",
    color: "#4ecbff",
    glow: "rgba(78, 203, 255, .38)",
    artSlot: 1,
  },
  nature: {
    name: "Natureza",
    short: "NA",
    color: "#7fe08d",
    glow: "rgba(127, 224, 141, .34)",
    artSlot: 2,
  },
  electric: {
    name: "Elétrico",
    short: "EL",
    color: "#ffd85e",
    glow: "rgba(255, 216, 94, .34)",
    artSlot: 3,
  },
  ice: {
    name: "Gelo",
    short: "GE",
    color: "#8fe9ff",
    glow: "rgba(143, 233, 255, .38)",
    artSlot: 4,
  },
  shadow: {
    name: "Sombrio",
    short: "SO",
    color: "#ba8cff",
    glow: "rgba(186, 140, 255, .38)",
    artSlot: 5,
  },
  neutral: {
    name: "Neutro",
    short: "NE",
    color: "#d8dfeb",
    glow: "rgba(216, 223, 235, .28)",
    artSlot: 6,
  },
};

export const emptyEnergyPool = (): EnergyPool => ({
  fire: 0,
  water: 0,
  nature: 0,
  electric: 0,
  ice: 0,
  shadow: 0,
  neutral: 0,
});

const attack = (
  id: string,
  name: string,
  element: Element,
  energy: 1 | 2 | 3,
  damage: number,
  minRoll: 2 | 3 | 4,
  animation: AttackDefinition["animation"],
  description: string,
  effect?: AttackDefinition["effect"],
): AttackDefinition => ({
  id,
  name,
  cost: { [element]: energy },
  damage,
  minRoll,
  animation,
  description,
  effect,
});

type CreatureSeed = Omit<CreatureDefinition, "attacks" | "artSlot"> & {
  moves: [string, string, string];
};

const elementAttacks: Record<
  Element,
  (seed: CreatureSeed) => CreatureDefinition["attacks"]
> = {
  fire: (seed) => [
    attack(`${seed.id}-1`, seed.moves[0], "fire", 1, 25, 2, "flame", "Uma chama precisa e confiável.", {
      type: "burn",
      chance: 20,
      duration: 2,
    }),
    attack(`${seed.id}-2`, seed.moves[1], "fire", 2, 60, 3, "flame", "Fogo concentrado com maior risco.", {
      type: "burn",
      chance: 35,
      duration: 2,
    }),
    attack(`${seed.id}-3`, seed.moves[2], "fire", 3, 100, 4, "flame", "Uma ofensiva devastadora alimentada por três energias.", {
      type: "burn",
      chance: 55,
      duration: 3,
    }),
  ],
  water: (seed) => [
    attack(`${seed.id}-1`, seed.moves[0], "water", 1, 22, 2, "wave", "Corrente rápida que desgasta o alvo."),
    attack(`${seed.id}-2`, seed.moves[1], "water", 2, 52, 3, "wave", "Uma maré que reduz o ritmo adversário.", {
      type: "soaked",
      chance: 40,
      duration: 2,
    }),
    attack(`${seed.id}-3`, seed.moves[2], "water", 3, 86, 4, "wave", "Água ancestral em pressão máxima.", {
      type: "heal",
      amount: 18,
    }),
  ],
  nature: (seed) => [
    attack(`${seed.id}-1`, seed.moves[0], "nature", 1, 20, 2, "nature", "Golpe firme que fortalece a postura."),
    attack(`${seed.id}-2`, seed.moves[1], "nature", 2, 48, 2, "nature", "Raízes e rochas controlam o terreno.", {
      type: "rooted",
      chance: 30,
      duration: 1,
    }),
    attack(`${seed.id}-3`, seed.moves[2], "nature", 3, 92, 4, "nature", "O campo inteiro responde ao guardião.", {
      type: "shield",
      amount: 20,
    }),
  ],
  electric: (seed) => [
    attack(`${seed.id}-1`, seed.moves[0], "electric", 1, 24, 2, "electric", "Investida veloz conduzida pela eletricidade."),
    attack(`${seed.id}-2`, seed.moves[1], "electric", 2, 55, 3, "electric", "Correntes elétricas aceleram o ataque.", {
      type: "shocked",
      chance: 35,
      duration: 1,
    }),
    attack(`${seed.id}-3`, seed.moves[2], "electric", 3, 94, 4, "electric", "Uma tempestade comprimida em um só impacto."),
  ],
  ice: (seed) => [
    attack(`${seed.id}-1`, seed.moves[0], "ice", 1, 22, 2, "ice", "Cristais frios atingem com precisão."),
    attack(`${seed.id}-2`, seed.moves[1], "ice", 2, 54, 3, "ice", "Uma corrente congelante reduz o ritmo do alvo.", {
      type: "soaked",
      chance: 35,
      duration: 2,
    }),
    attack(`${seed.id}-3`, seed.moves[2], "ice", 3, 96, 4, "ice", "O frio ancestral cobre toda a arena."),
  ],
  shadow: (seed) => [
    attack(`${seed.id}-1`, seed.moves[0], "shadow", 1, 21, 2, "shadow", "Eco sombrio que atravessa defesas comuns."),
    attack(`${seed.id}-2`, seed.moves[1], "shadow", 2, 50, 3, "shadow", "Um selo que perturba os sentidos.", {
      type: "haunted",
      chance: 40,
      duration: 2,
    }),
    attack(`${seed.id}-3`, seed.moves[2], "shadow", 3, 88, 4, "shadow", "Luz e sombra convergem num rito poderoso.", {
      type: "warded",
      chance: 100,
      duration: 1,
    }),
  ],
  neutral: (seed) => [
    attack(`${seed.id}-1`, seed.moves[0], "neutral", 1, 23, 2, "strike", "Um golpe versátil e confiável."),
    attack(`${seed.id}-2`, seed.moves[1], "neutral", 2, 52, 3, "strike", "Técnica adaptável que pune aberturas."),
    attack(`${seed.id}-3`, seed.moves[2], "neutral", 3, 90, 4, "strike", "Força pura concentrada num único ataque.", {
      type: "shield",
      amount: 14,
    }),
  ],
};

const seeds: CreatureSeed[] = [
  {
    id: "ignavora",
    name: "Ignavora",
    title: "Lagarta das Cinzas Vivas",
    description: "Guarda brasas antigas sob escamas de carvão.",
    lore: "Nasceu onde uma estrela tocou as colinas vulcânicas de Aurória.",
    inspiration: "Lendas universais de salamandras e fogos protetores",
    regionId: "roots",
    element: "fire",
    traits: ["chama", "cinzas"],
    rarity: "rare",
    role: "striker",
    hp: 120,
    defense: 42,
    speed: 58,
    moves: ["Chama Inicial", "Explosão Ancestral", "Fúria das Cinzas"],
    evolutionFamily: "ignavora",
    evolutionStage: 1,
    evolvesTo: "solvarya",
    obtainableBy: "Vínculo selvagem na Floresta das Raízes Antigas",
  },
  {
    id: "brasalume",
    name: "Brasalume",
    title: "Raposa do Lampião Errante",
    description: "Seu rastro acende trilhas seguras durante a noite.",
    lore: "Viajantes deixam fitas vermelhas para agradecer sua orientação.",
    inspiration: "Contos de luzes errantes e guardiões de estrada",
    regionId: "roots",
    element: "fire",
    traits: ["luz", "guia"],
    rarity: "uncommon",
    role: "skirmisher",
    hp: 104,
    defense: 36,
    speed: 76,
    moves: ["Faísca Guia", "Rastro Rubro", "Farol Incandescente"],
    obtainableBy: "Encontros ao crepúsculo",
  },
  {
    id: "caldeirante",
    name: "Caldeirante",
    title: "Touro da Forja Profunda",
    description: "Modela o solo com cascos aquecidos.",
    lore: "Ferreiros antigos diziam ouvir seu passo antes de uma grande descoberta.",
    inspiration: "Bestiários de forjas e animais tutelares",
    regionId: "desert",
    element: "fire",
    traits: ["metal", "vulcânico"],
    rarity: "epic",
    role: "guardian",
    hp: 168,
    defense: 72,
    speed: 31,
    moves: ["Casco Ígneo", "Forja Andante", "Coração de Magma"],
    obtainableBy: "Chefe regional da Forja Soterrada",
  },
  {
    id: "solvarya",
    name: "Solvarya",
    title: "Dragoa do Sol Velado",
    description: "Desperta quando o céu ganha a cor do cobre.",
    lore: "Seus círculos de voo marcam o início do calendário de Aurória.",
    inspiration: "Dragões solares reinterpretados para o atlas de Aurória",
    regionId: "desert",
    element: "fire",
    traits: ["solar", "dracônico"],
    rarity: "legendary",
    role: "striker",
    hp: 188,
    defense: 68,
    speed: 69,
    moves: ["Arco Solar", "Órbita Ardente", "Aurora da Fornalha"],
    evolutionFamily: "ignavora",
    evolutionStage: 2,
    obtainableBy: "Evolução de Ignavora após a Provação Solar",
  },
  {
    id: "cinerim",
    name: "Cinerim",
    title: "Pequeno Tecelão de Fuligem",
    description: "Desenha presságios em paredes usando cinzas.",
    lore: "Aparece perto de lareiras quando uma mudança se aproxima.",
    inspiration: "Espíritos domésticos de diferentes tradições europeias",
    regionId: "mist",
    element: "neutral",
    traits: ["doméstico", "presságio"],
    rarity: "common",
    role: "support",
    hp: 86,
    defense: 31,
    speed: 63,
    moves: ["Risco de Brasa", "Manto de Fuligem", "Presságio Carmesim"],
    obtainableBy: "Casas abandonadas no Pântano da Névoa",
  },
  {
    id: "marulino",
    name: "Marulino",
    title: "Lontra das Marés Cantantes",
    description: "Conversa com as correntes por meio de assobios.",
    lore: "Barcos perdidos seguem seu canto de volta aos arrecifes.",
    inspiration: "Lendas costeiras e animais-guia oceânicos",
    regionId: "archipelago",
    element: "water",
    traits: ["maré", "canto"],
    rarity: "common",
    role: "support",
    hp: 98,
    defense: 41,
    speed: 68,
    moves: ["Jato de Maré", "Canção das Correntes", "Abraço do Oceano"],
    evolutionFamily: "marulino",
    evolutionStage: 1,
    evolvesTo: "talassume",
    obtainableBy: "Encontro nos arrecifes do Arquipélago dos Espíritos",
  },
  {
    id: "coralume",
    name: "Coralume",
    title: "Cervo do Recife Lunar",
    description: "Galhadas de coral filtram a luz da lua.",
    lore: "Surge apenas quando as duas marés se encontram.",
    inspiration: "Cervos lunares e ecossistemas de recife",
    regionId: "deep-sea",
    element: "ice",
    traits: ["gelo", "lunar"],
    rarity: "rare",
    role: "controller",
    hp: 128,
    defense: 58,
    speed: 54,
    moves: ["Orvalho Frio", "Recife Lunar", "Maré de Cristal"],
    obtainableBy: "Santuário da Lua Submersa",
  },
  {
    id: "nevoante",
    name: "Nevoante",
    title: "Garça da Água Silenciosa",
    description: "Dissolve o próprio corpo em névoa fria.",
    lore: "Protege lagos usados como passagem entre o sonho e a vigília.",
    inspiration: "Aves aquáticas e contos de neblina do Leste Asiático",
    regionId: "archipelago",
    element: "water",
    traits: ["névoa", "evasão"],
    rarity: "uncommon",
    role: "skirmisher",
    hp: 100,
    defense: 38,
    speed: 82,
    moves: ["Bico de Névoa", "Passo Líquido", "Lago sem Margens"],
    obtainableBy: "Templos lacustres do arquipélago",
  },
  {
    id: "talassume",
    name: "Talassume",
    title: "Serpente do Abismo Azul",
    description: "Carrega pequenas ilhas sobre as placas dorsais.",
    lore: "Cartógrafos confundiram seu dorso adormecido com terra firme.",
    inspiration: "Serpentes marinhas presentes em tradições oceânicas",
    regionId: "deep-sea",
    element: "ice",
    traits: ["abissal", "gelo"],
    rarity: "legendary",
    role: "guardian",
    hp: 202,
    defense: 80,
    speed: 35,
    moves: ["Pressão Abissal", "Ilha Errante", "Dilúvio de Safira"],
    evolutionFamily: "marulino",
    evolutionStage: 2,
    obtainableBy: "Evolução de Marulino após cruzar o Mar das Profundezas",
  },
  {
    id: "geodril",
    name: "Geodril",
    title: "Escavador de Nascentes",
    description: "Encontra água doce sob a rocha mais seca.",
    lore: "Aldeias novas costumam nascer onde suas pegadas terminam.",
    inspiration: "Animais farejadores e mitos de fontes sagradas",
    regionId: "runic",
    element: "water",
    traits: ["subterrâneo", "fonte"],
    rarity: "common",
    role: "guardian",
    hp: 116,
    defense: 63,
    speed: 29,
    moves: ["Borrifo Mineral", "Veio d'Água", "Ruptura da Nascente"],
    obtainableBy: "Cavernas úmidas das Montanhas Rúnicas",
  },
  {
    id: "ibiram",
    name: "Ibirãm",
    title: "Guardião das Raízes Antigas",
    description: "Uma raposa coberta por folhas que escuta árvores centenárias.",
    lore: "É tratado pelos aldeões como mensageiro, nunca como animal doméstico.",
    inspiration: "Narrativas florestais sul-americanas, sem representar entidade sagrada específica",
    regionId: "roots",
    element: "nature",
    traits: ["natureza", "raízes"],
    rarity: "rare",
    role: "guardian",
    hp: 142,
    defense: 76,
    speed: 47,
    moves: ["Garra de Cipó", "Círculo das Raízes", "Memória da Mata"],
    evolutionFamily: "ibiram",
    evolutionStage: 1,
    evolvesTo: "arboran",
    obtainableBy: "Vínculo após restaurar três clareiras",
  },
  {
    id: "pedrassu",
    name: "Pedrassu",
    title: "Tatu da Serra Azul",
    description: "Enrola-se numa esfera de pedra riscada por minerais azuis.",
    lore: "Seus túneis arejam o solo e preservam sementes durante secas.",
    inspiration: "Fauna sul-americana e histórias de animais formadores da paisagem",
    regionId: "roots",
    element: "neutral",
    traits: ["montanha", "mineral"],
    rarity: "common",
    role: "guardian",
    hp: 134,
    defense: 82,
    speed: 24,
    moves: ["Rolamento Azul", "Couraça Serrana", "Falha Geológica"],
    obtainableBy: "Trilhas rochosas da Floresta das Raízes Antigas",
  },
  {
    id: "fungorim",
    name: "Fungorim",
    title: "Cervo dos Círculos Luminosos",
    description: "Cogumelos em suas galhadas revelam caminhos secretos.",
    lore: "Nunca cruza o mesmo círculo de pedras duas vezes.",
    inspiration: "Círculos feéricos e guardiões de bosque celtas",
    regionId: "fae-fields",
    element: "nature",
    traits: ["fungo", "feérico"],
    rarity: "uncommon",
    role: "support",
    hp: 118,
    defense: 55,
    speed: 52,
    moves: ["Esporo Sereno", "Círculo Verde", "Banquete do Bosque"],
    obtainableBy: "Campos Feéricos durante a lua crescente",
  },
  {
    id: "arboran",
    name: "Arboran",
    title: "Titã do Dossel",
    description: "Um bosque inteiro cresce sobre suas costas.",
    lore: "Move-se apenas quando uma floresta corre perigo real.",
    inspiration: "Homens-verdes, árvores cósmicas e gigantes protetores",
    regionId: "roots",
    element: "nature",
    traits: ["titã", "regeneração"],
    rarity: "legendary",
    role: "guardian",
    hp: 214,
    defense: 88,
    speed: 20,
    moves: ["Punho de Cedro", "Dossel Protetor", "Mundo de Raízes"],
    evolutionFamily: "ibiram",
    evolutionStage: 2,
    obtainableBy: "Evolução de Ibirãm no Santuário das Sete Sementes",
  },
  {
    id: "runacervo",
    name: "Runacervo",
    title: "Carneiro das Pedras Cantantes",
    description: "Seus chifres de cristal ressoam com inscrições antigas.",
    lore: "Cada impacto revela um fragmento esquecido da história das montanhas.",
    inspiration: "Runas nórdicas e carneiros monteses",
    regionId: "runic",
    element: "ice",
    traits: ["rúnico", "cristal"],
    rarity: "epic",
    role: "controller",
    hp: 158,
    defense: 79,
    speed: 40,
    moves: ["Chifre Rúnico", "Eco da Pedra", "Avalanche Gravada"],
    obtainableBy: "Provação das Pedras Cantantes",
  },
  {
    id: "raivel",
    name: "Raivel",
    title: "Lince das Nuvens Partidas",
    description: "Salta entre correntes de vento carregadas de eletricidade.",
    lore: "Seu miado antecede tempestades que limpam o céu por sete dias.",
    inspiration: "Felinos de montanha e animais associados às tempestades",
    regionId: "runic",
    element: "electric",
    traits: ["eletricidade", "tempestade"],
    rarity: "rare",
    role: "skirmisher",
    hp: 108,
    defense: 38,
    speed: 92,
    moves: ["Salto Voltaico", "Nuvem Partida", "Coroa da Tempestade"],
    evolutionFamily: "raivel",
    evolutionStage: 1,
    evolvesTo: "torvelume",
    obtainableBy: "Picos elétricos das Montanhas Rúnicas",
  },
  {
    id: "assobril",
    name: "Assobril",
    title: "Ave dos Sete Assobios",
    description: "Muda a direção do vento com sequências musicais.",
    lore: "Mensageiros antigos aprendiam suas rotas ouvindo-a ao amanhecer.",
    inspiration: "Aves mensageiras e tradições orais de navegação",
    regionId: "roots",
    element: "neutral",
    traits: ["música", "velocidade"],
    rarity: "common",
    role: "support",
    hp: 82,
    defense: 28,
    speed: 96,
    moves: ["Assobio Cortante", "Rota do Vento", "Canto dos Horizontes"],
    obtainableBy: "Copas altas da Floresta das Raízes Antigas",
  },
  {
    id: "kaminubo",
    name: "Kaminubo",
    title: "Peixe das Nuvens de Chuva",
    description: "Nada pelo céu antes das monções.",
    lore: "Agricultores acompanham sua sombra para preparar os campos.",
    inspiration: "Carpas celestes e narrativas de chuva do Sul e Leste da Ásia",
    regionId: "archipelago",
    element: "electric",
    traits: ["chuva", "eletricidade"],
    rarity: "uncommon",
    role: "controller",
    hp: 96,
    defense: 35,
    speed: 84,
    moves: ["Nado Celeste", "Cauda de Trovão", "Monção Ascendente"],
    obtainableBy: "Céu chuvoso do Arquipélago dos Espíritos",
  },
  {
    id: "torvelume",
    name: "Torvelume",
    title: "Quimera do Horizonte",
    description: "Traz auroras dentro das asas de tempestade.",
    lore: "Só pousa onde quatro caminhos do vento se cruzam.",
    inspiration: "Seres alados e ventos cardeais de múltiplas tradições",
    regionId: "runic",
    element: "electric",
    traits: ["aurora", "eletricidade"],
    rarity: "legendary",
    role: "striker",
    hp: 172,
    defense: 54,
    speed: 98,
    moves: ["Garra Boreal", "Espiral do Horizonte", "Tempestade das Quatro Rotas"],
    evolutionFamily: "raivel",
    evolutionStage: 2,
    obtainableBy: "Evolução de Raivel após dominar as quatro correntes",
  },
  {
    id: "zaravento",
    name: "Zaravento",
    title: "Cavalo da Planície Infinita",
    description: "Nunca deixa pegadas, apenas redemoinhos baixos.",
    lore: "Viajantes respeitosos recebem dele um atalho invisível.",
    inspiration: "Cavalos do vento de tradições das estepes",
    regionId: "fae-fields",
    element: "electric",
    traits: ["estepe", "evasão"],
    rarity: "epic",
    role: "skirmisher",
    hp: 132,
    defense: 45,
    speed: 94,
    moves: ["Casco de Brisa", "Atalho Invisível", "Galope Sem Fim"],
    obtainableBy: "Campos Feéricos em dias de vento forte",
  },
  {
    id: "lumissombra",
    name: "Lumissombra",
    title: "Lobo dos Dois Crepúsculos",
    description: "Seu pelo alterna entre luz lunar e penumbra violeta.",
    lore: "Guia memórias perdidas até os portões do sonho.",
    inspiration: "Cães psicopompos e lobos lunares reinterpretados",
    regionId: "eclipse",
    element: "shadow",
    traits: ["luz", "sombra"],
    rarity: "rare",
    role: "controller",
    hp: 122,
    defense: 50,
    speed: 73,
    moves: ["Mordida do Ocaso", "Passagem Lunar", "Eclipse Interior"],
    evolutionFamily: "lumissombra",
    evolutionStage: 1,
    evolvesTo: "eclipsara",
    obtainableBy: "Fendas do Reino do Eclipse",
  },
  {
    id: "sussurumi",
    name: "Sussurumi",
    title: "Mariposa dos Nomes Esquecidos",
    description: "Carrega palavras apagadas nas asas translúcidas.",
    lore: "Bibliotecas silenciosas são seu habitat favorito.",
    inspiration: "Mariposas como símbolos de memória e transformação",
    regionId: "mist",
    element: "shadow",
    traits: ["memória", "sonho"],
    rarity: "common",
    role: "support",
    hp: 78,
    defense: 30,
    speed: 81,
    moves: ["Pó de Lembrança", "Nome Velado", "Biblioteca dos Sonhos"],
    obtainableBy: "Ruínas do Pântano da Névoa Eterna",
  },
  {
    id: "ankhara",
    name: "Ankhara",
    title: "Felina do Sol Sepultado",
    description: "Protege câmaras antigas com selos de luz dourada.",
    lore: "Não serve a reis; vigia somente o equilíbrio entre passado e presente.",
    inspiration: "Felinos solares e guardiões funerários do nordeste africano",
    regionId: "desert",
    element: "neutral",
    traits: ["solar", "proteção"],
    rarity: "epic",
    role: "guardian",
    hp: 154,
    defense: 74,
    speed: 61,
    moves: ["Garra Hierática", "Selo Dourado", "Sol Sepultado"],
    obtainableBy: "Santuário das Câmaras Douradas",
  },
  {
    id: "eclipsara",
    name: "Eclipsara",
    title: "Regente do Limiar Astral",
    description: "Mantém luz e sombra em órbitas iguais.",
    lore: "Sua aparição encerra eras de desequilíbrio espiritual.",
    inspiration: "Eclipses e guardiões de passagem presentes em mitologias diversas",
    regionId: "eclipse",
    element: "shadow",
    traits: ["eclipse", "astral"],
    rarity: "mythic",
    role: "controller",
    hp: 196,
    defense: 72,
    speed: 86,
    moves: ["Órbita Violeta", "Balança Astral", "Noite do Meio-Dia"],
    evolutionFamily: "lumissombra",
    evolutionStage: 2,
    obtainableBy: "Evolução de Lumissombra durante um evento de eclipse",
    eventExclusive: true,
  },
  {
    id: "kodamiru",
    name: "Kodamiru",
    title: "Eco do Bosque de Bambu",
    description: "Pequeno espírito que faz nós de luz nos galhos.",
    lore: "Cada nó marca uma promessa cumprida por um viajante.",
    inspiration: "Espíritos arbóreos do folclore japonês, reinterpretados com respeito",
    regionId: "archipelago",
    element: "shadow",
    traits: ["bambu", "luz"],
    rarity: "uncommon",
    role: "support",
    hp: 90,
    defense: 43,
    speed: 66,
    moves: ["Nó de Luz", "Eco do Bambu", "Promessa do Bosque"],
    obtainableBy: "Bosques do Arquipélago dos Espíritos",
  },
];

export const CREATURES: CreatureDefinition[] = seeds.map((seed) => ({
  ...seed,
  attacks: elementAttacks[seed.element](seed),
  artSlot: ELEMENT_META[seed.element].artSlot,
}));

export const CREATURE_BY_ID = new Map(CREATURES.map((creature) => [creature.id, creature]));

export const STARTER_TEAM_IDS = [
  "ignavora",
  "marulino",
  "ibiram",
  "raivel",
  "lumissombra",
  "pedrassu",
] as const;

export const NPC_TEAM_IDS = [
  "fungorim",
  "brasalume",
  "nevoante",
  "assobril",
  "sussurumi",
  "geodril",
] as const;

export const REGIONS: RegionDefinition[] = [
  {
    id: "roots",
    name: "Floresta das Raízes Antigas",
    subtitle: "Onde árvores guardam pactos e caminhos",
    inspiration: "Lendas florestais brasileiras e sul-americanas",
    recommendedLevel: "1–12",
    discovered: 6,
    totalCreatures: 24,
    status: "open",
    mapPosition: { x: 22, y: 50 },
    activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"],
    accent: "#5be29a",
  },
  {
    id: "archipelago",
    name: "Arquipélago dos Espíritos",
    subtitle: "Templos, marés e promessas antigas",
    inspiration: "Narrativas costeiras e do Leste Asiático",
    recommendedLevel: "8–20",
    discovered: 2,
    totalCreatures: 28,
    status: "open",
    mapPosition: { x: 50, y: 75 },
    activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"],
    accent: "#55d4ff",
  },
  {
    id: "runic",
    name: "Montanhas Rúnicas",
    subtitle: "Pedra cantante sob céus elétricos",
    inspiration: "Lendas nórdicas e tradições das montanhas",
    recommendedLevel: "15–28",
    discovered: 1,
    totalCreatures: 26,
    status: "open",
    mapPosition: { x: 48, y: 18 },
    activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"],
    accent: "#ffd45a",
  },
  {
    id: "desert",
    name: "Deserto dos Reis Esquecidos",
    subtitle: "O sol vigia câmaras soterradas",
    inspiration: "Narrativas do Egito e de regiões desérticas",
    recommendedLevel: "24–38",
    discovered: 0,
    totalCreatures: 31,
    status: "locked",
    mapPosition: { x: 82, y: 27 },
    activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"],
    accent: "#ffac5c",
  },
  {
    id: "eclipse",
    name: "Reino do Eclipse",
    subtitle: "Uma fronteira entre memória e vazio",
    inspiration: "Arquétipos de eclipses e mundos liminares",
    recommendedLevel: "40+",
    discovered: 0,
    totalCreatures: 34,
    status: "event",
    mapPosition: { x: 82, y: 55 },
    activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"],
    accent: "#b48cff",
  },
];

export const IMPLEMENTATION_NOTE = {
  completeCreatures: CREATURES.length,
  catalogTarget: 405,
  statement:
    "Esta fundação contém criaturas completas e jogáveis. O catálogo está preparado para 405, mas as demais serão adicionadas em lotes revisados; nomes isolados não são contados como criaturas prontas.",
};
