import type { CreatureSeed } from "../creature-seed";

export const ARCHIPELAGO_CREATURE_SEEDS: CreatureSeed[] = [
  {
      id: "iara", name: "Iara", title: "Senhora do Canto das Águas",
      description: "Encantada dos rios amazônicos cuja voz atrai quem se aproxima de suas margens.",
      lore: "A figura brasileira reúne camadas indígenas e europeias; versões modernas a descrevem como mulher de beleza extraordinária ligada às águas doces.",
      folklore: { tradition: "Folclore amazônico brasileiro", origin: "Amazônia, Brasil", sourceNote: "A narrativa mudou ao longo do tempo; a adaptação reconhece essa formação histórica em vez de declarar uma versão única.", adaptation: "Preserva o canto, o rio e a agência da encantada, evitando tratá-la como monstro aquático genérico." },
      regionId: "archipelago", element: "water", traits: ["encantada", "canto", "rio"], rarity: "epic", role: "controller",
      hp: 120, defense: 48, speed: 70, moves: ["Voz da Margem", "Espelho do Rio", "Canto da Iara"],
      obtainableBy: "Encontro ritual nas águas calmas do arquipélago", spriteIndex: 5,
    },
  {
      id: "boto-cor-de-rosa", name: "Boto-cor-de-rosa", title: "Encantado das Festas Ribeirinhas",
      description: "Boto amazônico que assume forma humana para visitar festas à margem do rio.",
      lore: "Costuma aparecer vestido de branco e com chapéu, retornando às águas antes do amanhecer.",
      folklore: { tradition: "Folclore amazônico brasileiro", origin: "Amazônia, Brasil", sourceNote: "A história explica encontros misteriosos e vínculos com o rio em comunidades ribeirinhas.", adaptation: "A batalha usa sua forma de boto e sua transformação como ilusão, sem substituir o animal por um humano genérico." },
      regionId: "archipelago", element: "water", traits: ["encantado", "transformação", "rio"], rarity: "rare", role: "skirmisher",
      hp: 110, defense: 42, speed: 86, moves: ["Salto Rosado", "Chapéu Branco", "Retorno ao Rio"],
      obtainableBy: "Festividades ribeirinhas do Arquipélago dos Espíritos", spriteIndex: 6,
    },
  {
      id: "kappa", name: "Kappa", title: "Habitante dos Rios Japoneses",
      description: "Yōkai anfíbio reconhecido pela carapaça, pelo bico e pelo prato de água sobre a cabeça.",
      lore: "Pode ser perigoso, mas também respeita etiqueta e promessas; ao se curvar, derrama a água que sustenta sua força.",
      folklore: { tradition: "Folclore japonês", origin: "Japão", sourceNote: "Há muitas descrições regionais, geralmente ligadas a rios, lagos e advertências sobre a água.", adaptation: "Preserva carapaça, prato d'água, pepino e regras de cortesia." },
      regionId: "archipelago", element: "water", traits: ["yōkai", "anfíbio", "etiqueta"], rarity: "uncommon", role: "guardian",
      hp: 146, defense: 78, speed: 38, moves: ["Bico de Rio", "Prato Cheio", "Desafio do Kappa"],
      obtainableBy: "Margens protegidas por oferendas de pepino", spriteIndex: 8,
    },
  {
      id: "tengu", name: "Tengu", title: "Habitante dos Ventos da Montanha",
      description: "Ser sobrenatural japonês de montanha, ligado a aves, ventos e artes marciais.",
      lore: "Representações antigas tendem ao aspecto de ave; formas posteriores incluem rosto vermelho e nariz longo.",
      folklore: { tradition: "Folclore e tradição religiosa japonesa", origin: "Japão", sourceNote: "Tengu variam de espíritos perigosos a protetores e mestres, conforme período e narrativa.", adaptation: "Usa a forma alada antiga e evita reduzi-lo à caricatura de nariz longo." },
      regionId: "archipelago", element: "storm", traits: ["montanha", "ave", "marcial"], rarity: "epic", role: "controller",
      hp: 134, defense: 56, speed: 88, moves: ["Leque de Rajada", "Passo da Montanha", "Vendaval do Tengu"],
      obtainableBy: "Templos elevados do Arquipélago dos Espíritos", spriteIndex: 17,
    },
  {
      id: "qilin", name: "Qilin", title: "Presságio de Governo Justo",
      description: "Ser auspicioso chinês de corpo ungulado, associado à benevolência e ao surgimento de sábios.",
      lore: "É descrito como tão gentil que evita pisar em seres vivos; sua aparência combina traços animais sem equivaler ao unicórnio europeu.",
      folklore: { tradition: "Mitologia chinesa", origin: "China", sourceNote: "Iconografia e descrições mudaram entre dinastias e regiões do Leste Asiático.", adaptation: "Mantém cascos, escamas, chifres e temperamento benevolente; não o chama de dragão ou unicórnio." },
      regionId: "archipelago", element: "spirit", traits: ["auspicioso", "ungulado", "benevolente"], rarity: "legendary", role: "support",
      hp: 180, defense: 80, speed: 66, moves: ["Passo sem Dano", "Sopro Auspicioso", "Chegada do Qilin"],
      obtainableBy: "Provação de benevolência no arquipélago", spriteIndex: 22,
    },
  {
      id: "umibozu", name: "Umibōzu", title: "Sombra sobre o Mar",
      description: "Aparição marítima gigantesca que surge em águas calmas ou tempestades repentinas.",
      lore: "Marinheiros japoneses contam que a figura escura pode virar embarcações ou exigir um barril, sendo vencida por astúcia em algumas versões.",
      folklore: { tradition: "Folclore marítimo japonês", origin: "Japão", sourceNote: "Forma, tamanho e comportamento variam entre regiões costeiras.", adaptation: "Mantém a silhueta escura, a escala marítima e o encontro com navegantes." },
      regionId: "archipelago", element: "water", traits: ["marítimo", "gigante", "aparição"], rarity: "epic", role: "guardian",
      hp: 206, defense: 86, speed: 24, moves: ["Onda Silenciosa", "Pedido do Barril", "Noite sobre o Mar"], obtainableBy: "Abismo dos Espíritos", spriteIndex: 5, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
  {
      id: "ningyo", name: "Ningyo", title: "Oráculo das Correntes",
      description: "Ser aquático japonês de aparência variável, frequentemente ligado a presságios.",
      lore: "Registros e contos descrevem combinações entre peixe e traços humanos; capturá-lo pode anunciar desastres ou longevidade em narrativas distintas.",
      folklore: { tradition: "Folclore japonês", origin: "Japão", sourceNote: "Não equivale à sereia europeia e possui iconografias variadas.", adaptation: "Preserva a forma híbrida aquática e o papel de presságio." },
      regionId: "archipelago", element: "water", traits: ["aquático", "oráculo", "presságio"], rarity: "rare", role: "support",
      hp: 120, defense: 52, speed: 78, moves: ["Escama Oracular", "Voz da Corrente", "Maré do Presságio"], obtainableBy: "Templo das Marés", spriteIndex: 6, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
  {
      id: "selkie", name: "Selkie", title: "Viajante da Pele de Foca",
      description: "Ser capaz de deixar a pele de foca para assumir forma humana em terra.",
      lore: "Baladas e contos do Atlântico Norte narram amores e cativeiros ligados ao esconderijo da pele que permite seu retorno ao mar.",
      folklore: { tradition: "Folclores escocês e das ilhas do Atlântico Norte", origin: "Escócia, Orkney e Shetland", sourceNote: "O tom varia entre romance, perda e advertência.", adaptation: "Mantém a pele de foca como centro da metamorfose e evita tratá-la como sereia." },
      regionId: "archipelago", element: "spirit", traits: ["foca", "metamorfa", "marítima"], rarity: "rare", role: "skirmisher",
      hp: 126, defense: 48, speed: 88, moves: ["Pele Guardada", "Passo na Praia", "Retorno às Ondas"], obtainableBy: "Ilhas das Promessas", spriteIndex: 7, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
  {
      id: "bake-kujira", name: "Bake-kujira", title: "Esqueleto da Baleia Fantasma",
      description: "Esqueleto espectral de baleia que atravessa o mar acompanhado por aves e peixes incomuns.",
      lore: "Uma narrativa associada à costa de Shimane descreve pescadores encontrando a aparição e os infortúnios que seguiram sua aproximação.",
      folklore: { tradition: "Folclore japonês", origin: "Shimane, Japão", sourceNote: "É uma narrativa regional moderna em comparação com yōkai muito antigos.", adaptation: "Mantém a baleia esquelética, o cortejo animal e o caráter de aparição." },
      regionId: "archipelago", element: "spirit", traits: ["baleia", "esquelético", "fantasma"], rarity: "legendary", role: "controller",
      hp: 188, defense: 72, speed: 40, moves: ["Canto Oco", "Cortejo do Mar", "Maré Fantasma"], obtainableBy: "Recife Ancestral", spriteIndex: 8, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
  {
      id: "nokk", name: "Nøkk", title: "Cavalo das Águas Escuras",
      description: "Espírito aquático metamórfico que pode surgir como cavalo junto a rios e lagos.",
      lore: "Tradições escandinavas narram encontros perigosos, música e mudanças de forma ligadas à água.",
      folklore: { tradition: "Folclores escandinavos", origin: "Escandinávia", sourceNote: "Nomes e formas variam entre línguas e regiões nórdicas.", adaptation: "Usa a forma equina aquática e mantém sua natureza metamórfica." },
      regionId: "archipelago", element: "water", traits: ["equino", "metamorfo", "lacustre"], rarity: "epic", role: "controller",
      hp: 148, defense: 62, speed: 84, moves: ["Galope Submerso", "Canção da Margem", "Forma do Nøkk"], obtainableBy: "Cais Cartógrafo", spriteIndex: 9, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
];
