import type { CreatureSeed } from "../creature-seed";

export const DESERT_CREATURE_SEEDS: CreatureSeed[] = [
  {
      id: "salamandra", name: "Salamandra", title: "Habitante das Chamas",
      description: "Ser associado ao fogo em bestiários medievais e na tradição alquímica europeia.",
      lore: "A resistência real das salamandras ao calor de troncos úmidos alimentou relatos de animais capazes de viver dentro do fogo.",
      folklore: { tradition: "Bestiários e alquimia europeia", origin: "Europa medieval e moderna", sourceNote: "A salamandra tornou-se um emblema do elemento fogo em textos naturalistas e ocultistas.", adaptation: "Usa a forma anfíbia tradicional, sem transformá-la em um dragão genérico." },
      regionId: "desert", element: "fire", traits: ["anfíbio", "alquímico", "resistente"], rarity: "uncommon", role: "support",
      hp: 104, defense: 56, speed: 54, moves: ["Passo na Brasa", "Selo Alquímico", "Forno da Salamandra"],
      obtainableBy: "Oficinas abandonadas do Deserto dos Reis Esquecidos", spriteIndex: 2,
    },
  {
      id: "fenix", name: "Fênix", title: "Ave do Retorno Solar",
      description: "Ave extraordinária que encerra e reinicia o próprio ciclo de vida pelo fogo.",
      lore: "Autores greco-romanos narraram uma ave única e longeva ligada ao Sol, cuja renovação foi posteriormente associada às cinzas.",
      folklore: { tradition: "Mitologia greco-romana", origin: "Mediterrâneo antigo", sourceNote: "A tradição clássica dialoga com aves solares egípcias, mas não as trata aqui como uma única entidade.", adaptation: "Preserva a ave solar, a longevidade e o renascimento sem acrescentar anatomia monstruosa." },
      regionId: "desert", element: "fire", traits: ["ave", "solar", "renascimento"], rarity: "legendary", role: "support",
      hp: 166, defense: 58, speed: 84, moves: ["Pena Solar", "Voo das Cinzas", "Ciclo da Fênix"],
      obtainableBy: "Santuário solar do deserto", spriteIndex: 3,
    },
  {
      id: "ziz", name: "Ziz", title: "Ave Imensa dos Céus",
      description: "Ave colossal da tradição judaica cuja envergadura alcança os limites do céu.",
      lore: "Textos e comentários a colocam entre os grandes seres da criação, ao lado de Behemoth e Leviatã.",
      folklore: { tradition: "Mitologia e literatura rabínica judaica", origin: "Oriente Médio", sourceNote: "Descrições enfatizam escala cósmica e domínio do céu, não uma espécie comum de monstro.", adaptation: "Preserva a ave colossal e o papel celeste sem fundi-la com outras aves míticas." },
      regionId: "desert", element: "storm", traits: ["ave", "colossal", "celeste"], rarity: "mythic", role: "guardian",
      hp: 212, defense: 82, speed: 62, moves: ["Bater de Asas", "Sombra do Horizonte", "Céu de Ziz"],
      obtainableBy: "Evento celeste sobre o Deserto dos Reis Esquecidos", eventExclusive: true, spriteIndex: 18,
    },
  {
      id: "simurgh", name: "Simurgh", title: "Ave Sábia da Tradição Persa",
      description: "Ave benevolente e antiquíssima associada à sabedoria, cura e proteção.",
      lore: "Na literatura persa, acolhe Zāl e o auxilia por meio de uma pena; outras tradições a ligam à árvore de todas as sementes.",
      folklore: { tradition: "Mitologia e literatura persa", origin: "Irã e mundo persófono", sourceNote: "A Simurgh atravessa períodos pré-islâmicos e obras como o Shahnameh, com funções que variam.", adaptation: "Preserva a grande ave sábia, as penas protetoras e o vínculo com árvores e cura." },
      regionId: "desert", element: "storm", traits: ["ave", "sabedoria", "cura"], rarity: "legendary", role: "support",
      hp: 176, defense: 70, speed: 78, moves: ["Pena Protetora", "Voo sobre Alborz", "Sabedoria da Simurgh"],
      obtainableBy: "Santuário elevado além do deserto", spriteIndex: 19,
    },
  {
      id: "ammit", name: "Ammit", title: "Devoradora dos Corações",
      description: "Ser funerário egípcio com partes de crocodilo, leão e hipopótamo.",
      lore: "Permanece junto à pesagem do coração e devora aquele considerado indigno, impedindo sua continuidade no além.",
      folklore: { tradition: "Religião e mitologia do Egito Antigo", origin: "Egito Antigo", sourceNote: "Sua função é ligada ao julgamento funerário, não à caça aleatória.", adaptation: "Preserva a anatomia composta e o papel de consequência do julgamento." },
      regionId: "desert", element: "nature", traits: ["composto", "julgamento", "funerário"], rarity: "legendary", role: "guardian",
      hp: 218, defense: 92, speed: 32, moves: ["Mandíbula do Julgamento", "Peso do Coração", "Sentença de Ammit"], obtainableBy: "Tumba dos Reis", spriteIndex: 20, spriteSheet: "/art/folklore-creatures-second-atlas-chibi-portraits-v1.webp",
    },
  {
      id: "manticora", name: "Manticora", title: "Predadora dos Relatos Persas",
      description: "Criatura descrita por autores antigos com corpo leonino, rosto humano e cauda perigosa.",
      lore: "Relatos gregos sobre a Pérsia transmitiram e transformaram sua imagem, que depois entrou em bestiários europeus.",
      folklore: { tradition: "Relatos antigos e bestiários medievais", origin: "Pérsia em fontes gregas", sourceNote: "A transmissão histórica produziu variações importantes de anatomia.", adaptation: "Usa corpo de leão, face humana estilizada e cauda armada sem declarar uma forma única." },
      regionId: "desert", element: "fire", traits: ["leonino", "cauda", "bestiário"], rarity: "epic", role: "striker",
      hp: 166, defense: 62, speed: 80, moves: ["Cauda de Espinhos", "Salto Leonino", "Rugido da Manticora"], obtainableBy: "Ossário Colossal", spriteIndex: 21, spriteSheet: "/art/folklore-creatures-second-atlas-chibi-portraits-v1.webp",
    },
  {
      id: "esfinge", name: "Esfinge", title: "Guardiã dos Limiares Sagrados",
      description: "Ser leonino de cabeça humana associado à proteção monumental e à autoridade régia no Egito Antigo.",
      lore: "A esfinge egípcia e a esfinge grega possuem histórias distintas; esta entrada segue o motivo guardião egípcio.",
      folklore: { tradition: "Iconografia e religião do Egito Antigo", origin: "Egito Antigo", sourceNote: "Não funde o guardião egípcio com o enigma da tradição grega.", adaptation: "Mantém corpo de leão, cabeça humana e função protetora." },
      regionId: "desert", element: "spirit", traits: ["leonino", "guardião", "monumental"], rarity: "legendary", role: "controller",
      hp: 186, defense: 84, speed: 48, moves: ["Vigília de Pedra", "Palavra Régia", "Limiar da Esfinge"], obtainableBy: "Ruínas do Sol", spriteIndex: 22, spriteSheet: "/art/folklore-creatures-second-atlas-chibi-portraits-v1.webp",
    },
  {
      id: "roc", name: "Roc", title: "Ave que Oculta o Sol",
      description: "Ave gigantesca das narrativas de viagem do mundo árabe e persa.",
      lore: "Histórias difundidas nas Mil e Uma Noites descrevem sua força para erguer animais enormes e sua escala quase inacreditável.",
      folklore: { tradition: "Literatura árabe e persa de viagens maravilhosas", origin: "Oceano Índico imaginado e Oriente Médio", sourceNote: "A grafia Rukh/Roc e os cenários variam entre traduções.", adaptation: "Preserva a ave colossal e a força de voo sem fundi-la com outras aves míticas." },
      regionId: "desert", element: "storm", traits: ["ave", "colossal", "viajante"], rarity: "mythic", role: "guardian",
      hp: 224, defense: 78, speed: 68, moves: ["Garra do Roc", "Sombra do Sol", "Voo do Horizonte"], obtainableBy: "Portão de Areia", spriteIndex: 23, spriteSheet: "/art/folklore-creatures-second-atlas-chibi-portraits-v1.webp",
    },
  {
      id: "ifrit", name: "Ifrit", title: "Espírito de Fogo Rebelde",
      description: "Classe poderosa de jinn associada ao fogo e a forças extraordinárias em tradições islâmicas e árabes.",
      lore: "Textos e narrativas posteriores descrevem ifrits com temperamentos e papéis diversos, não como uma espécie uniforme de demônio.",
      folklore: { tradition: "Tradições islâmicas e folclores árabes", origin: "Oriente Médio", sourceNote: "Conceitos religiosos e narrativos variam por fonte e época.", adaptation: "Representa um jinn ígneo poderoso sem reduzir toda a categoria a antagonistas." },
      regionId: "desert", element: "fire", traits: ["jinn", "fogo", "poderoso"], rarity: "epic", role: "striker",
      hp: 156, defense: 58, speed: 84, moves: ["Punho de Brasa", "Vento do Ifrit", "Coluna de Fogo"], obtainableBy: "Oásis Oculto", spriteIndex: 24, spriteSheet: "/art/folklore-creatures-second-atlas-chibi-portraits-v1.webp",
    },
];
