import type { CreatureSeed } from "../creature-seed";

export const MIST_CREATURE_SEEDS: CreatureSeed[] = [
  {
      id: "mula-sem-cabeca", name: "Mula-sem-cabeça", title: "Galope da Noite em Chamas",
      description: "Mula encantada que atravessa a noite com fogo irrompendo do pescoço.",
      lore: "A lenda brasileira possui muitas versões sobre a maldição e costuma situar sua cavalgada entre a noite de quinta e a manhã de sexta-feira.",
      folklore: { tradition: "Folclore brasileiro", origin: "Brasil", sourceNote: "Narrativa difundida em várias regiões, com versões diferentes para a origem e a quebra do encanto.", adaptation: "Evita fixar uma única causa moral da maldição e preserva a forma, o galope e as chamas." },
      regionId: "mist", element: "fire", traits: ["encantado", "galope", "noturno"], rarity: "epic", role: "skirmisher",
      hp: 132, defense: 46, speed: 90, moves: ["Coice de Faísca", "Galope Maldito", "Clarão sem Cabeça"],
      obtainableBy: "Encontro noturno nas estradas do Pântano da Névoa", spriteIndex: 1,
    },
  {
      id: "aitvaras", name: "Aitvaras", title: "Espírito do Rastro Flamejante",
      description: "Espírito doméstico lituano que pode aparecer como ave ou ser voador de cauda ardente.",
      lore: "Diz-se que leva riqueza para a casa que o abriga, embora os presentes possam ter sido tomados de outros.",
      folklore: { tradition: "Folclore lituano", origin: "Lituânia", sourceNote: "Relatos variam entre formas de galo, serpente e criatura aérea semelhante a um pequeno dragão.", adaptation: "Combina a forma de ave-serpente e o rastro de fogo sem apagar sua natureza doméstica ambígua." },
      regionId: "mist", element: "fire", traits: ["doméstico", "aéreo", "ambíguo"], rarity: "rare", role: "controller",
      hp: 112, defense: 40, speed: 82, moves: ["Rastro Rubro", "Presente Tomado", "Telhado em Chamas"],
      obtainableBy: "Telhados antigos do Pântano da Névoa", spriteIndex: 4,
    },
  {
      id: "leshy", name: "Leshy", title: "Senhor Mutável da Floresta",
      description: "Espírito eslavo da floresta capaz de alterar tamanho e imitar vozes.",
      lore: "Pode desorientar viajantes, esconder animais e mudar de aparência conforme atravessa seu domínio.",
      folklore: { tradition: "Folclores eslavos", origin: "Europa Oriental e regiões eslavas", sourceNote: "Nome, temperamento e aparência variam entre tradições locais.", adaptation: "Preserva a mudança de tamanho, os sinais vegetais e a soberania sobre a mata." },
      regionId: "mist", element: "nature", traits: ["espírito", "metamorfo", "floresta"], rarity: "epic", role: "controller",
      hp: 154, defense: 74, speed: 52, moves: ["Voz Imitada", "Passo sem Trilha", "Estatura do Leshy"],
      obtainableBy: "Bosques móveis do Pântano da Névoa", spriteIndex: 13,
    },
  {
      id: "domovoi", name: "Domovoi", title: "Espírito Guardião da Casa",
      description: "Espírito doméstico eslavo que protege a família e o lar quando é respeitado.",
      lore: "Ruídos noturnos, pequenos trabalhos e advertências são atribuídos a ele; abandono ou desrespeito podem torná-lo hostil.",
      folklore: { tradition: "Folclores eslavos", origin: "Europa Oriental e regiões eslavas", sourceNote: "Aparência e costumes variam, muitas vezes associados à lareira, ao celeiro e aos ancestrais da casa.", adaptation: "Preserva pequena estatura, pelos, vínculo ancestral e papel doméstico." },
      regionId: "mist", element: "spirit", traits: ["doméstico", "ancestral", "guardião"], rarity: "uncommon", role: "support",
      hp: 102, defense: 60, speed: 48, moves: ["Ruído no Assoalho", "Cuidado da Lareira", "Aviso do Domovoi"],
      obtainableBy: "Casas cuidadas no Pântano da Névoa", spriteIndex: 21,
    },
  {
      id: "kikimora", name: "Kikimora", title: "Presença Atrás do Fogão",
      description: "Espírito doméstico eslavo associado a ruídos, fiação e presságios dentro da casa.",
      lore: "Pode ajudar uma casa bem cuidada ou perturbar seus moradores, dependendo da tradição e da relação com o lar.",
      folklore: { tradition: "Folclores eslavos", origin: "Europa Oriental", sourceNote: "Há versões domésticas e versões ligadas a pântanos.", adaptation: "Combina pequena figura doméstica e sinais do brejo sem tratá-los como forma universal." },
      regionId: "mist", element: "spirit", traits: ["doméstico", "fiandeira", "presságio"], rarity: "uncommon", role: "controller",
      hp: 98, defense: 52, speed: 70, moves: ["Fio Embaraçado", "Ruído na Parede", "Presságio da Kikimora"], obtainableBy: "Casa da Névoa", spriteIndex: 15, spriteSheet: "/art/folklore-creatures-second-atlas-chibi-portraits-v1.webp",
    },
  {
      id: "rusalka", name: "Rusalka", title: "Espírito das Águas Verdes",
      description: "Figura feminina sobrenatural ligada a rios, lagos, vegetação e períodos do calendário eslavo.",
      lore: "As descrições variam muito por época e região, indo de presenças férteis a aparições perigosas.",
      folklore: { tradition: "Folclores eslavos", origin: "Europa Oriental", sourceNote: "Não corresponde exatamente à sereia marítima ocidental.", adaptation: "Mantém o vínculo com água doce, cabelos e vegetação, reconhecendo sua variedade." },
      regionId: "mist", element: "water", traits: ["água doce", "vegetação", "aparição"], rarity: "rare", role: "controller",
      hp: 116, defense: 46, speed: 78, moves: ["Cabelo de Junco", "Canto do Lago", "Dança da Rusalka"], obtainableBy: "Charco dos Ecos", spriteIndex: 16, spriteSheet: "/art/folklore-creatures-second-atlas-chibi-portraits-v1.webp",
    },
  {
      id: "puca", name: "Púca", title: "Metamorfo dos Caminhos",
      description: "Ser do folclore irlandês que assume várias formas animais, frequentemente a de um cavalo escuro.",
      lore: "Pode assustar, aconselhar ou levar viajantes a corridas imprevisíveis, conforme a narrativa.",
      folklore: { tradition: "Folclore irlandês", origin: "Irlanda", sourceNote: "Grafia, temperamento e formas mudam entre regiões e traduções.", adaptation: "Usa a forma equina negra como uma dentre várias possibilidades." },
      regionId: "mist", element: "spirit", traits: ["metamorfo", "equino", "travesso"], rarity: "epic", role: "skirmisher",
      hp: 142, defense: 54, speed: 96, moves: ["Salto do Caminho", "Forma Imprevista", "Corrida do Púca"], obtainableBy: "Bosque Móvel", spriteIndex: 17, spriteSheet: "/art/folklore-creatures-second-atlas-chibi-portraits-v1.webp",
    },
  {
      id: "dullahan", name: "Dullahan", title: "Cavaleiro sem Cabeça",
      description: "Cavaleiro sobrenatural irlandês que carrega a própria cabeça e anuncia a morte.",
      lore: "Quando interrompe sua cavalgada e pronuncia um nome, o destino anunciado se cumpre em muitos relatos.",
      folklore: { tradition: "Folclore irlandês", origin: "Irlanda", sourceNote: "Detalhes sobre montaria, carruagem e objetos carregados variam.", adaptation: "Mantém a cabeça carregada, o cavalo e o papel de mensageiro fatal." },
      regionId: "mist", element: "spirit", traits: ["cavaleiro", "sem cabeça", "presságio"], rarity: "legendary", role: "striker",
      hp: 178, defense: 70, speed: 86, moves: ["Rédea Sombria", "Nome Derradeiro", "Cavalgada do Dullahan"], obtainableBy: "Vila Afundada", spriteIndex: 18, spriteSheet: "/art/folklore-creatures-second-atlas-chibi-portraits-v1.webp",
    },
  {
      id: "fogo-fatuo", name: "Fogo-fátuo", title: "Luz que Desvia Viajantes",
      description: "Luz errante vista sobre pântanos e caminhos, cercada por explicações naturais e narrativas sobrenaturais.",
      lore: "Muitas culturas descrevem luzes que afastam viajantes da estrada ou marcam lugares de memória e perigo.",
      folklore: { tradition: "Folclores europeus e narrativas difundidas globalmente", origin: "Múltiplas regiões", sourceNote: "Nomes e interpretações locais não são equivalentes entre si.", adaptation: "Transforma o motivo da luz errante em criatura sem atribuir uma origem única." },
      regionId: "mist", element: "fire", traits: ["luz", "errante", "pântano"], rarity: "common", role: "skirmisher",
      hp: 82, defense: 28, speed: 112, moves: ["Faísca Errante", "Desvio da Trilha", "Brilho do Brejo"], obtainableBy: "Margem Enevoada", spriteIndex: 19, spriteSheet: "/art/folklore-creatures-second-atlas-chibi-portraits-v1.webp",
    },
];
