import type { CreatureSeed } from "../creature-seed";

export const ROOTS_CREATURE_SEEDS: CreatureSeed[] = [
  {
      id: "boitata", name: "Boitatá", title: "Serpente de Fogo da Mata",
      description: "Serpente luminosa que vigia campos e florestas contra quem os destrói.",
      lore: "Relatos brasileiros descrevem olhos ou corpo em chamas e sua função de confundir ou punir invasores da mata.",
      folklore: { tradition: "Folclore brasileiro de matriz tupi", origin: "Brasil", sourceNote: "Registrado desde o período colonial, com variações regionais sobre uma serpente ou fogo vivo protetor.", adaptation: "Mantém a forma serpentina, o brilho ígneo e o papel de guardião da natureza." },
      regionId: "roots", element: "fire", traits: ["serpente", "guardião", "luminoso"], rarity: "rare", role: "striker",
      hp: 124, defense: 44, speed: 72, moves: ["Olhar de Brasa", "Rastro Incandescente", "Círculo do Boitatá"],
      obtainableBy: "Provação do fogo guardião na Floresta das Raízes Antigas", spriteIndex: 0,
    },
  {
      id: "curupira", name: "Curupira", title: "Guardião dos Pés Virados",
      description: "Guardião da mata de cabelos vermelhos e pés voltados para trás.",
      lore: "Engana caçadores e invasores com rastros invertidos, assobios e caminhos que parecem mudar de lugar.",
      folklore: { tradition: "Folclore brasileiro de matriz indígena", origin: "Brasil", sourceNote: "É uma das figuras florestais mais antigas registradas no Brasil, com muitas variações regionais.", adaptation: "Preserva a forma humana pequena, os cabelos vermelhos, os pés invertidos e a proteção dos animais." },
      regionId: "roots", element: "nature", traits: ["guardião", "pés invertidos", "floresta"], rarity: "rare", role: "controller",
      hp: 126, defense: 58, speed: 88, moves: ["Rastro Invertido", "Assobio da Mata", "Labirinto do Curupira"],
      obtainableBy: "Trilha de rastros invertidos na Floresta das Raízes Antigas", spriteIndex: 10,
    },
  {
      id: "caipora", name: "Caipora", title: "Protetora dos Animais da Mata",
      description: "Entidade guardiã que confunde caçadores e protege os animais silvestres.",
      lore: "Sua aparência varia conforme a região; é frequentemente associada a assobios, fumo, montaria em porco-do-mato e pactos de respeito.",
      folklore: { tradition: "Folclore brasileiro de matriz indígena", origin: "Brasil", sourceNote: "As tradições de Caipora e Curupira se aproximam em algumas regiões, mas não são tratadas como idênticas aqui.", adaptation: "Usa uma representação regional de guardiã montada e explicita que outras formas existem." },
      regionId: "roots", element: "nature", traits: ["guardião", "animais", "assobio"], rarity: "rare", role: "support",
      hp: 132, defense: 64, speed: 76, moves: ["Chamado da Queixada", "Fumo de Trégua", "Pacto da Caipora"],
      obtainableBy: "Missão de proteção da fauna nas Raízes Antigas", spriteIndex: 11,
    },
  {
      id: "mapinguari", name: "Mapinguari", title: "Gigante das Matas Distantes",
      description: "Ser enorme e coberto de pelos que habita áreas profundas da floresta amazônica.",
      lore: "Os relatos variam: força extraordinária, cheiro marcante e anatomias incomuns aparecem em diferentes versões da tradição oral.",
      folklore: { tradition: "Folclore amazônico", origin: "Amazônia, Brasil", sourceNote: "Não há uma aparência única; descrições mudam entre povos, épocas e regiões.", adaptation: "Assume uma forma bípede robusta e evita declarar características controversas como universais." },
      regionId: "roots", element: "nature", traits: ["gigante", "floresta", "resistente"], rarity: "epic", role: "guardian",
      hp: 204, defense: 88, speed: 24, moves: ["Passo Pesado", "Rugido da Mata", "Investida do Mapinguari"],
      obtainableBy: "Chefe selvagem das trilhas mais profundas", spriteIndex: 12,
    },
  {
      id: "saci-perere", name: "Saci-Pererê", title: "Travesso do Redemoinho",
      description: "Figura de uma perna só e gorro vermelho que viaja em redemoinhos e prega peças.",
      lore: "Esconde objetos, embaraça crinas, assusta viajantes e pode ser capturado, segundo versões populares, por meio de seu redemoinho e gorro.",
      folklore: { tradition: "Folclore brasileiro", origin: "Brasil", sourceNote: "A figura reúne influências indígenas, africanas e europeias e mudou bastante entre registros históricos.", adaptation: "Preserva uma perna, gorro vermelho, cachimbo em versões modernas e domínio do redemoinho." },
      regionId: "roots", element: "storm", traits: ["travesso", "redemoinho", "gorro"], rarity: "rare", role: "skirmisher",
      hp: 104, defense: 34, speed: 98, moves: ["Pulo de Vento", "Nó na Crina", "Redemoinho do Saci"],
      obtainableBy: "Encontro com um redemoinho nas trilhas das Raízes", spriteIndex: 15,
    },
  {
      id: "matinta-pereira", name: "Matinta Pereira", title: "Assobio da Noite Amazônica",
      description: "Figura encantada anunciada por um assobio agudo durante a noite.",
      lore: "Em narrativas amazônicas, pode assumir forma de ave ou de uma pessoa idosa e cobrar a promessa de tabaco feita para silenciar seu assobio.",
      folklore: { tradition: "Folclore amazônico", origin: "Amazônia, Brasil", sourceNote: "Os relatos variam entre localidades e alternam formas humanas, aviárias e encantadas.", adaptation: "Preserva o assobio, a metamorfose e a promessa; evita fixar uma única aparência como universal." },
      regionId: "roots", element: "spirit", traits: ["metamorfa", "assobio", "noturna"], rarity: "rare", role: "controller",
      hp: 118, defense: 48, speed: 82, moves: ["Assobio Distante", "Promessa da Noite", "Voo da Matinta"], obtainableBy: "Clareira dos Sussurros", spriteIndex: 0, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
  {
      id: "cobra-grande", name: "Cobra Grande", title: "Serpente dos Rios Profundos",
      description: "Serpente colossal associada aos rios e às transformações da paisagem amazônica.",
      lore: "Também chamada Boiúna em diferentes narrativas, desloca águas, cria caminhos e inspira cautela nas margens durante a noite.",
      folklore: { tradition: "Folclore amazônico", origin: "Amazônia, Brasil", sourceNote: "Nomes, dimensões e feitos mudam entre comunidades ribeirinhas.", adaptation: "Mantém o vínculo com rios, tamanho extraordinário e presença noturna." },
      regionId: "roots", element: "water", traits: ["serpente", "fluvial", "colossal"], rarity: "epic", role: "guardian",
      hp: 198, defense: 84, speed: 34, moves: ["Cauda de Corrente", "Olhos da Boiúna", "Rio sem Margem"], obtainableBy: "Coração das Raízes", spriteIndex: 1, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
  {
      id: "anhanga", name: "Anhangá", title: "Protetor de Olhos de Fogo",
      description: "Presença protetora da mata frequentemente descrita em forma de veado branco.",
      lore: "Relatos de matriz tupi o relacionam à defesa dos animais e ao castigo de caçadores que violam os pactos da floresta.",
      folklore: { tradition: "Tradições indígenas brasileiras registradas historicamente", origin: "Brasil", sourceNote: "Grafias e interpretações variam, e nem toda tradição o descreve da mesma maneira.", adaptation: "Usa a forma de cervo branco e olhos luminosos como uma representação, não como definição única." },
      regionId: "roots", element: "nature", traits: ["cervo", "guardião", "luminoso"], rarity: "legendary", role: "support",
      hp: 174, defense: 80, speed: 76, moves: ["Passo Branco", "Olhar Protetor", "Pacto de Anhangá"], obtainableBy: "Ruínas da Guardiã", spriteIndex: 2, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
  {
      id: "comadre-fulozinha", name: "Comadre Fulozinha", title: "Guardiã dos Cabelos Longos",
      description: "Encantada da mata nordestina que protege animais e desorienta quem desrespeita seu território.",
      lore: "Seu assobio, seus cabelos e a oferta de fumo aparecem em narrativas do Nordeste brasileiro, com muitas formas locais.",
      folklore: { tradition: "Folclore do Nordeste brasileiro", origin: "Nordeste do Brasil", sourceNote: "Características variam por estado e tradição oral.", adaptation: "Preserva o papel guardião, o assobio e os longos cabelos sem misturá-la à Caipora." },
      regionId: "roots", element: "nature", traits: ["encantada", "guardiã", "assobio"], rarity: "rare", role: "skirmisher",
      hp: 124, defense: 52, speed: 90, moves: ["Trança da Mata", "Assobio Cruzado", "Caminho de Fulozinha"], obtainableBy: "Trilha Invertida", spriteIndex: 3, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
  {
      id: "uirapuru-encantado", name: "Uirapuru Encantado", title: "Canto que Silencia a Floresta",
      description: "Ave de canto extraordinário cercada por narrativas de encanto, sorte e transformação.",
      lore: "Histórias amazônicas explicam seu canto raro por amores, metamorfoses e promessas, em versões que mudam de narrador para narrador.",
      folklore: { tradition: "Narrativas amazônicas", origin: "Amazônia, Brasil", sourceNote: "O pássaro real e as narrativas encantadas convivem sem formar uma única versão canônica.", adaptation: "Amplifica o canto como poder de apoio e mantém a pequena forma aviária." },
      regionId: "roots", element: "storm", traits: ["ave", "canto", "encantado"], rarity: "uncommon", role: "support",
      hp: 96, defense: 36, speed: 102, moves: ["Canto Raro", "Pausa da Mata", "Voo Encantado"], obtainableBy: "Portal da Mata", spriteIndex: 4, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
];
