import type { CreatureSeed } from "../creature-seed";

export const RUNIC_CREATURE_SEEDS: CreatureSeed[] = [
  {
      id: "amarok", name: "Amarok", title: "Lobo Solitário da Noite",
      description: "Lobo gigantesco da tradição inuíte que caça sozinho.",
      lore: "Histórias sobre Amarok advertem caçadores imprudentes e contrastam sua caça solitária com a alcateia comum.",
      folklore: { tradition: "Tradições inuítes", origin: "Regiões árticas da América do Norte", sourceNote: "A grafia e os relatos variam entre línguas e comunidades inuítes.", adaptation: "Mantém o lobo gigantesco e solitário; evita misturá-lo a lobisomens europeus." },
      regionId: "runic", element: "nature", traits: ["lobo", "ártico", "solitário"], rarity: "legendary", role: "striker",
      hp: 184, defense: 72, speed: 80, moves: ["Mordida Solitária", "Caçada Polar", "Uivo do Amarok"],
      obtainableBy: "Caçada ritual nas Montanhas Rúnicas", spriteIndex: 14,
    },
  {
      id: "raiju", name: "Raijū", title: "Besta do Trovão",
      description: "Yōkai associado ao relâmpago, descrito em formas animais como lobo, cão ou felino.",
      lore: "É ligado a Raijin e aos fenômenos das tempestades; relatos populares explicam marcas e danos causados por raios.",
      folklore: { tradition: "Folclore japonês", origin: "Japão", sourceNote: "A forma não é fixa e varia entre compilações e regiões.", adaptation: "Usa uma forma canina feita de nuvens e eletricidade, uma das representações tradicionais." },
      regionId: "runic", element: "storm", traits: ["yōkai", "relâmpago", "canino"], rarity: "rare", role: "striker",
      hp: 116, defense: 42, speed: 94, moves: ["Pata de Raio", "Salto entre Nuvens", "Rugido do Raijū"],
      obtainableBy: "Picos atingidos por relâmpagos nas Montanhas Rúnicas", spriteIndex: 16,
    },
  {
      id: "carbunclo", name: "Carbunclo", title: "Pequeno Portador de Luz",
      description: "Animal esquivo de relatos sul-americanos, reconhecido por uma pedra ou brilho precioso na cabeça.",
      lore: "Buscadores de tesouro o descrevem como uma luz móvel na noite; persegui-lo pode revelar riqueza ou levar o ganancioso a se perder.",
      folklore: { tradition: "Folclores mineiros sul-americanos", origin: "Região andina e Cone Sul", sourceNote: "Carbunclo ou carbúnculo aparece em relatos com formas animais diferentes, sempre ligado a brilho e tesouro.", adaptation: "Usa um pequeno quadrúpede com gema luminosa e mantém a aparência variável como parte do bestiário." },
      regionId: "runic", element: "spirit", traits: ["luminoso", "tesouro", "esquivo"], rarity: "rare", role: "skirmisher",
      hp: 108, defense: 46, speed: 92, moves: ["Clarão da Gema", "Rastro Precioso", "Tesouro do Carbunclo"],
      obtainableBy: "Minas antigas das Montanhas Rúnicas", spriteIndex: 24,
    },
  {
      id: "thunderbird", name: "Pássaro do Trovão", title: "Asas que Chamam a Tempestade",
      description: "Grande ser aviário associado ao trovão e aos relâmpagos em diversas tradições indígenas norte-americanas.",
      lore: "Não existe uma versão única: nomes, relações e significados pertencem a povos específicos e não devem ser fundidos em uma narrativa genérica.",
      folklore: { tradition: "Tradições de diferentes povos indígenas da América do Norte", origin: "América do Norte", sourceNote: "Esta entrada reconhece a diversidade e não substitui as narrativas próprias de cada povo.", adaptation: "Representa apenas o motivo amplo de ave e tempestade, sem copiar símbolos cerimoniais específicos." },
      regionId: "runic", element: "storm", traits: ["ave", "trovão", "celeste"], rarity: "mythic", role: "striker",
      hp: 190, defense: 70, speed: 90, moves: ["Bater do Trovão", "Olhar de Relâmpago", "Tempestade Celeste"], obtainableBy: "Pico do Trovão", spriteIndex: 10, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
  {
      id: "alicanto", name: "Alicanto", title: "Ave dos Veios Minerais",
      description: "Ave noturna chilena cujas penas brilham conforme o metal ou minério de que se alimenta.",
      lore: "Mineiros seguem sua luz para encontrar riqueza, mas a ganância ou uma perseguição descuidada pode conduzir a precipícios.",
      folklore: { tradition: "Folclore mineiro chileno", origin: "Chile", sourceNote: "O brilho e a dieta mineral distinguem versões de ouro e de prata.", adaptation: "Mantém a ave luminosa e sua ligação ambígua com tesouros subterrâneos." },
      regionId: "runic", element: "spirit", traits: ["ave", "minério", "luminoso"], rarity: "rare", role: "support",
      hp: 110, defense: 46, speed: 92, moves: ["Pena Metálica", "Rastro de Prata", "Veio do Alicanto"], obtainableBy: "Mina do Carbunclo", spriteIndex: 11, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
  {
      id: "fenghuang", name: "Fenghuang", title: "Ave da Harmonia Imperial",
      description: "Ave auspiciosa chinesa associada à harmonia, virtude e renovação da ordem.",
      lore: "Sua iconografia reúne traços simbólicos de diferentes aves e se desenvolveu por muitos períodos da história chinesa.",
      folklore: { tradition: "Mitologia e iconografia chinesa", origin: "China", sourceNote: "Não é simplesmente uma fênix ocidental; sua história e seus significados são próprios.", adaptation: "Preserva a ave composta, a dignidade e a associação à harmonia." },
      regionId: "runic", element: "fire", traits: ["ave", "auspicioso", "harmonia"], rarity: "legendary", role: "support",
      hp: 168, defense: 66, speed: 82, moves: ["Pluma das Virtudes", "Dança dos Ventos", "Harmonia do Fenghuang"], obtainableBy: "Santuário do Céu", spriteIndex: 12, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
  {
      id: "yeti", name: "Yeti", title: "Habitante das Alturas Nevadas",
      description: "Ser misterioso associado às montanhas e neves do Himalaia.",
      lore: "Relatos locais, traduções e explorações estrangeiras produziram imagens diferentes, nem sempre equivalentes ao popular 'abominável homem das neves'.",
      folklore: { tradition: "Narrativas himalaias", origin: "Região do Himalaia", sourceNote: "Termos e interpretações variam entre comunidades e línguas locais.", adaptation: "Usa uma forma peluda de montanha e evita apresentar especulação moderna como tradição única." },
      regionId: "runic", element: "nature", traits: ["montanha", "peludo", "neve"], rarity: "epic", role: "guardian",
      hp: 210, defense: 90, speed: 30, moves: ["Punho da Geleira", "Passo na Neve", "Eco do Himalaia"], obtainableBy: "Passagem Glacial", spriteIndex: 13, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
  {
      id: "ratatoskr", name: "Ratatoskr", title: "Mensageiro da Árvore do Mundo",
      description: "Esquilo que corre pelo tronco de Yggdrasil levando palavras entre a águia e o dragão.",
      lore: "Na Edda em Prosa, suas mensagens alimentam a disputa entre os seres que habitam as extremidades da árvore cósmica.",
      folklore: { tradition: "Mitologia nórdica registrada nas Eddas", origin: "Escandinávia medieval", sourceNote: "A fonte preservada é breve, deixando muitos detalhes visuais em aberto.", adaptation: "Mantém o esquilo mensageiro e a corrida vertical pela árvore do mundo." },
      regionId: "runic", element: "nature", traits: ["esquilo", "mensageiro", "ágil"], rarity: "uncommon", role: "skirmisher",
      hp: 92, defense: 32, speed: 108, moves: ["Recado Afiado", "Corrida no Tronco", "Rumor de Yggdrasil"], obtainableBy: "Ponte Rúnica", spriteIndex: 14, spriteSheet: "/art/folklore-creatures-second-atlas.png",
    },
];
