import type { AttackDefinition, CreatureDefinition, Element } from "../types";

type CreatureSeed = Omit<CreatureDefinition, "attacks" | "sprite"> & {
  moves: [string, string, string];
  spriteIndex: number;
  spriteSheet?: string;
};

const SPRITE_SHEET = "/art/folklore-creatures-five-elements.png";
const SECOND_SPRITE_SHEET = "/art/folklore-creatures-second-atlas.png";
const SPRITE_COLUMNS = 5;
const SPRITE_ROWS = 5;

function attack(
  id: string,
  name: string,
  element: Element,
  energy: 1 | 2 | 3,
  damage: number,
  minRoll: 2 | 3 | 4,
  animation: AttackDefinition["animation"],
  description: string,
  effect?: AttackDefinition["effect"],
): AttackDefinition {
  return { id, name, cost: { [element]: energy }, damage, minRoll, animation, description, effect };
}

const attackFactory: Record<Element, (seed: CreatureSeed) => CreatureDefinition["attacks"]> = {
  fire: (seed) => [
    attack(`${seed.id}-1`, seed.moves[0], "fire", 1, 22, 2, "flame", "Ataque direto com chance de deixar o alvo em chamas.", { type: "burn", chance: 20, amount: 7, duration: 2 }),
    attack(`${seed.id}-2`, seed.moves[1], "fire", 2, 50, 3, "flame", "Uma descarga de calor concentrado.", { type: "burn", chance: 35, amount: 8, duration: 2 }),
    attack(`${seed.id}-3`, seed.moves[2], "fire", 3, 86, 4, "flame", "A manifestação mais intensa da criatura.", { type: "burn", chance: 55, amount: 10, duration: 3 }),
  ],
  water: (seed) => [
    attack(`${seed.id}-1`, seed.moves[0], "water", 1, 20, 2, "wave", "Um golpe fluido e confiável."),
    attack(`${seed.id}-2`, seed.moves[1], "water", 2, 45, 3, "wave", "Encharca o alvo e o deixa vulnerável à Tempestade.", { type: "soaked", chance: 45, duration: 2 }),
    attack(`${seed.id}-3`, seed.moves[2], "water", 3, 74, 4, "wave", "A corrente restaura parte da vitalidade de quem a conduz.", { type: "heal", amount: 20 }),
  ],
  nature: (seed) => [
    attack(`${seed.id}-1`, seed.moves[0], "nature", 1, 18, 2, "nature", "Ataque firme ligado ao território."),
    attack(`${seed.id}-2`, seed.moves[1], "nature", 2, 43, 2, "nature", "Prende os passos do alvo e bloqueia trocas voluntárias.", { type: "rooted", chance: 35, duration: 1 }),
    attack(`${seed.id}-3`, seed.moves[2], "nature", 3, 78, 4, "nature", "O terreno responde e forma uma proteção viva.", { type: "shield", amount: 22 }),
  ],
  storm: (seed) => [
    attack(`${seed.id}-1`, seed.moves[0], "storm", 1, 21, 2, "storm", "Um movimento veloz conduzido pelo vento."),
    attack(`${seed.id}-2`, seed.moves[1], "storm", 2, 48, 3, "storm", "A descarga dificulta a próxima ação do alvo.", { type: "shocked", chance: 35, duration: 1 }),
    attack(`${seed.id}-3`, seed.moves[2], "storm", 3, 82, 4, "storm", "Céu e vento convergem em um único impacto."),
  ],
  spirit: (seed) => [
    attack(`${seed.id}-1`, seed.moves[0], "spirit", 1, 19, 2, "spirit", "Um eco sobrenatural que enfraquece a ofensiva inimiga.", { type: "haunted", chance: 25, duration: 1 }),
    attack(`${seed.id}-2`, seed.moves[1], "spirit", 2, 44, 3, "spirit", "Um rito defensivo acompanha o golpe.", { type: "warded", chance: 100, duration: 2 }),
    attack(`${seed.id}-3`, seed.moves[2], "spirit", 3, 76, 4, "spirit", "A presença ancestral ocupa toda a arena.", { type: "heal", amount: 16 }),
  ],
};

const seeds: CreatureSeed[] = [
  {
    id: "boitata", name: "Boitatá", title: "Serpente de Fogo da Mata",
    description: "Serpente luminosa que vigia campos e florestas contra quem os destrói.",
    lore: "Relatos brasileiros descrevem olhos ou corpo em chamas e sua função de confundir ou punir invasores da mata.",
    folklore: { tradition: "Folclore brasileiro de matriz tupi", origin: "Brasil", sourceNote: "Registrado desde o período colonial, com variações regionais sobre uma serpente ou fogo vivo protetor.", adaptation: "Mantém a forma serpentina, o brilho ígneo e o papel de guardião da natureza." },
    regionId: "roots", element: "fire", traits: ["serpente", "guardião", "luminoso"], rarity: "rare", role: "striker",
    hp: 124, defense: 44, speed: 72, moves: ["Olhar de Brasa", "Rastro Incandescente", "Círculo do Boitatá"],
    obtainableBy: "Provação do fogo guardião na Floresta das Raízes Antigas", spriteIndex: 0,
  },
  {
    id: "mula-sem-cabeca", name: "Mula-sem-cabeça", title: "Galope da Noite em Chamas",
    description: "Mula encantada que atravessa a noite com fogo irrompendo do pescoço.",
    lore: "A lenda brasileira possui muitas versões sobre a maldição e costuma situar sua cavalgada entre a noite de quinta e a manhã de sexta-feira.",
    folklore: { tradition: "Folclore brasileiro", origin: "Brasil", sourceNote: "Narrativa difundida em várias regiões, com versões diferentes para a origem e a quebra do encanto.", adaptation: "Evita fixar uma única causa moral da maldição e preserva a forma, o galope e as chamas." },
    regionId: "mist", element: "fire", traits: ["encantado", "galope", "noturno"], rarity: "epic", role: "skirmisher",
    hp: 132, defense: 46, speed: 90, moves: ["Coice de Faísca", "Galope Maldito", "Clarão sem Cabeça"],
    obtainableBy: "Encontro noturno nas estradas do Pântano da Névoa", spriteIndex: 1,
  },
  {
    id: "salamandra", name: "Salamandra", title: "Habitante das Chamas",
    description: "Ser associado ao fogo em bestiários medievais e na tradição alquímica europeia.",
    lore: "A resistência real das salamandras ao calor de troncos úmidos alimentou relatos de animais capazes de viver dentro do fogo.",
    folklore: { tradition: "Bestiários e alquimia europeia", origin: "Europa medieval e moderna", sourceNote: "A salamandra tornou-se um emblema do elemento fogo em textos naturalistas e ocultistas.", adaptation: "Usa a forma anfíbia tradicional, sem transformá-la em um dragão genérico." },
    regionId: "desert", element: "fire", traits: ["anfíbio", "alquímico", "resistente"], rarity: "uncommon", role: "support",
    hp: 104, defense: 56, speed: 54, moves: ["Passo na Brasa", "Selo Alquímico", "Forno da Salamandra"],
    obtainableBy: "Oficinas abandonadas do Deserto dos Reis Esquecidos", spriteIndex: 2,
  },
  {
    id: "fenix", name: "Fênix", title: "Ave do Retorno Solar",
    description: "Ave extraordinária que encerra e reinicia o próprio ciclo de vida pelo fogo.",
    lore: "Autores greco-romanos narraram uma ave única e longeva ligada ao Sol, cuja renovação foi posteriormente associada às cinzas.",
    folklore: { tradition: "Mitologia greco-romana", origin: "Mediterrâneo antigo", sourceNote: "A tradição clássica dialoga com aves solares egípcias, mas não as trata aqui como uma única entidade.", adaptation: "Preserva a ave solar, a longevidade e o renascimento sem acrescentar anatomia monstruosa." },
    regionId: "desert", element: "fire", traits: ["ave", "solar", "renascimento"], rarity: "legendary", role: "support",
    hp: 166, defense: 58, speed: 84, moves: ["Pena Solar", "Voo das Cinzas", "Ciclo da Fênix"],
    obtainableBy: "Santuário solar do deserto", spriteIndex: 3,
  },
  {
    id: "aitvaras", name: "Aitvaras", title: "Espírito do Rastro Flamejante",
    description: "Espírito doméstico lituano que pode aparecer como ave ou ser voador de cauda ardente.",
    lore: "Diz-se que leva riqueza para a casa que o abriga, embora os presentes possam ter sido tomados de outros.",
    folklore: { tradition: "Folclore lituano", origin: "Lituânia", sourceNote: "Relatos variam entre formas de galo, serpente e criatura aérea semelhante a um pequeno dragão.", adaptation: "Combina a forma de ave-serpente e o rastro de fogo sem apagar sua natureza doméstica ambígua." },
    regionId: "mist", element: "fire", traits: ["doméstico", "aéreo", "ambíguo"], rarity: "rare", role: "controller",
    hp: 112, defense: 40, speed: 82, moves: ["Rastro Rubro", "Presente Tomado", "Telhado em Chamas"],
    obtainableBy: "Telhados antigos do Pântano da Névoa", spriteIndex: 4,
  },
  {
    id: "iara", name: "Iara", title: "Senhora do Canto das Águas",
    description: "Encantada dos rios amazônicos cuja voz atrai quem se aproxima de suas margens.",
    lore: "A figura brasileira reúne camadas indígenas e europeias; versões modernas a descrevem como mulher de beleza extraordinária ligada às águas doces.",
    folklore: { tradition: "Folclore amazônico brasileiro", origin: "Amazônia, Brasil", sourceNote: "A narrativa mudou ao longo do tempo; a adaptação reconhece essa formação histórica em vez de declarar uma versão única.", adaptation: "Preserva o canto, o rio e a agência da encantada, evitando tratá-la como monstro aquático genérico." },
    regionId: "archipelago", element: "water", traits: ["encantada", "canto", "rio"], rarity: "epic", role: "controller",
    hp: 120, defense: 48, speed: 70, moves: ["Voz da Margem", "Espelho do Rio", "Canto da Iara"],
    obtainableBy: "Encontro ritual nas águas calmas do arquipélago", spriteIndex: 5,
  },
  {
    id: "boto-cor-de-rosa", name: "Boto-cor-de-rosa", title: "Encantado das Festas Ribeirinhas",
    description: "Boto amazônico que assume forma humana para visitar festas à margem do rio.",
    lore: "Costuma aparecer vestido de branco e com chapéu, retornando às águas antes do amanhecer.",
    folklore: { tradition: "Folclore amazônico brasileiro", origin: "Amazônia, Brasil", sourceNote: "A história explica encontros misteriosos e vínculos com o rio em comunidades ribeirinhas.", adaptation: "A batalha usa sua forma de boto e sua transformação como ilusão, sem substituir o animal por um humano genérico." },
    regionId: "archipelago", element: "water", traits: ["encantado", "transformação", "rio"], rarity: "rare", role: "skirmisher",
    hp: 110, defense: 42, speed: 86, moves: ["Salto Rosado", "Chapéu Branco", "Retorno ao Rio"],
    obtainableBy: "Festividades ribeirinhas do Arquipélago dos Espíritos", spriteIndex: 6,
  },
  {
    id: "kelpie", name: "Kelpie", title: "Cavalo das Águas Profundas",
    description: "Espírito aquático escocês que assume a forma de cavalo junto a rios e lagos.",
    lore: "Atrai viajantes para o dorso e os leva para a água; algumas versões permitem dominá-lo ao tomar suas rédeas.",
    folklore: { tradition: "Folclore escocês", origin: "Escócia", sourceNote: "Pertence a um conjunto amplo de tradições célticas sobre cavalos d'água.", adaptation: "Mantém forma equina, crina molhada e comportamento traiçoeiro." },
    regionId: "deep-sea", element: "water", traits: ["equino", "metamorfo", "lago"], rarity: "rare", role: "striker",
    hp: 136, defense: 54, speed: 78, moves: ["Casco de Lago", "Rédea Encharcada", "Mergulho do Kelpie"],
    obtainableBy: "Lagos escuros do Mar das Profundezas", spriteIndex: 7,
  },
  {
    id: "kappa", name: "Kappa", title: "Habitante dos Rios Japoneses",
    description: "Yōkai anfíbio reconhecido pela carapaça, pelo bico e pelo prato de água sobre a cabeça.",
    lore: "Pode ser perigoso, mas também respeita etiqueta e promessas; ao se curvar, derrama a água que sustenta sua força.",
    folklore: { tradition: "Folclore japonês", origin: "Japão", sourceNote: "Há muitas descrições regionais, geralmente ligadas a rios, lagos e advertências sobre a água.", adaptation: "Preserva carapaça, prato d'água, pepino e regras de cortesia." },
    regionId: "archipelago", element: "water", traits: ["yōkai", "anfíbio", "etiqueta"], rarity: "uncommon", role: "guardian",
    hp: 146, defense: 78, speed: 38, moves: ["Bico de Rio", "Prato Cheio", "Desafio do Kappa"],
    obtainableBy: "Margens protegidas por oferendas de pepino", spriteIndex: 8,
  },
  {
    id: "ahuizotl", name: "Ahuízotl", title: "Caçador das Águas Mexicas",
    description: "Ser aquático de aspecto canino ou mustelídeo, com uma mão na extremidade da cauda.",
    lore: "Fontes coloniais registraram que atraía pessoas para a água e usava a mão caudal para capturá-las.",
    folklore: { tradition: "Tradição mexica registrada no período colonial", origin: "Vale do México", sourceNote: "É descrito em fontes como o Códice Florentino, com variações de interpretação zoológica e mítica.", adaptation: "Mantém corpo aquático e mão caudal; não o converte em lontra comum." },
    regionId: "deep-sea", element: "water", traits: ["aquático", "mão caudal", "caçador"], rarity: "epic", role: "controller",
    hp: 138, defense: 58, speed: 74, moves: ["Garra da Cauda", "Chamado da Margem", "Poço do Ahuízotl"],
    obtainableBy: "Ruínas lacustres do Mar das Profundezas", spriteIndex: 9,
  },
  {
    id: "curupira", name: "Curupira", title: "Guardião dos Pés Virados",
    description: "Guardião da mata de cabelos vermelhos e pés voltados para trás.",
    lore: "Engana caçadores e invasores com rastros invertidos, assobios e caminhos que parecem mudar de lugar.",
    folklore: { tradition: "Folclore brasileiro de matriz indígena", origin: "Brasil", sourceNote: "É uma das figuras florestais mais antigas registradas no Brasil, com muitas variações regionais.", adaptation: "Preserva a forma humana pequena, os cabelos vermelhos, os pés invertidos e a proteção dos animais." },
    regionId: "roots", element: "nature", traits: ["guardião", "pés invertidos", "floresta"], rarity: "rare", role: "controller",
    hp: 126, defense: 58, speed: 88, moves: ["Rastro Invertido", "Assobio da Mata", "Labirinto do Curupira"],
    obtainableBy: "Trilha de rastros invertidos na Floresta das Raízes Antigas", spriteIndex: 10,
  },
  {
    id: "caipora", name: "Caipora", title: "Protetora dos Animais da Mata",
    description: "Entidade guardiã que confunde caçadores e protege os animais silvestres.",
    lore: "Sua aparência varia conforme a região; é frequentemente associada a assobios, fumo, montaria em porco-do-mato e pactos de respeito.",
    folklore: { tradition: "Folclore brasileiro de matriz indígena", origin: "Brasil", sourceNote: "As tradições de Caipora e Curupira se aproximam em algumas regiões, mas não são tratadas como idênticas aqui.", adaptation: "Usa uma representação regional de guardiã montada e explicita que outras formas existem." },
    regionId: "roots", element: "nature", traits: ["guardião", "animais", "assobio"], rarity: "rare", role: "support",
    hp: 132, defense: 64, speed: 76, moves: ["Chamado da Queixada", "Fumo de Trégua", "Pacto da Caipora"],
    obtainableBy: "Missão de proteção da fauna nas Raízes Antigas", spriteIndex: 11,
  },
  {
    id: "mapinguari", name: "Mapinguari", title: "Gigante das Matas Distantes",
    description: "Ser enorme e coberto de pelos que habita áreas profundas da floresta amazônica.",
    lore: "Os relatos variam: força extraordinária, cheiro marcante e anatomias incomuns aparecem em diferentes versões da tradição oral.",
    folklore: { tradition: "Folclore amazônico", origin: "Amazônia, Brasil", sourceNote: "Não há uma aparência única; descrições mudam entre povos, épocas e regiões.", adaptation: "Assume uma forma bípede robusta e evita declarar características controversas como universais." },
    regionId: "roots", element: "nature", traits: ["gigante", "floresta", "resistente"], rarity: "epic", role: "guardian",
    hp: 204, defense: 88, speed: 24, moves: ["Passo Pesado", "Rugido da Mata", "Investida do Mapinguari"],
    obtainableBy: "Chefe selvagem das trilhas mais profundas", spriteIndex: 12,
  },
  {
    id: "leshy", name: "Leshy", title: "Senhor Mutável da Floresta",
    description: "Espírito eslavo da floresta capaz de alterar tamanho e imitar vozes.",
    lore: "Pode desorientar viajantes, esconder animais e mudar de aparência conforme atravessa seu domínio.",
    folklore: { tradition: "Folclores eslavos", origin: "Europa Oriental e regiões eslavas", sourceNote: "Nome, temperamento e aparência variam entre tradições locais.", adaptation: "Preserva a mudança de tamanho, os sinais vegetais e a soberania sobre a mata." },
    regionId: "mist", element: "nature", traits: ["espírito", "metamorfo", "floresta"], rarity: "epic", role: "controller",
    hp: 154, defense: 74, speed: 52, moves: ["Voz Imitada", "Passo sem Trilha", "Estatura do Leshy"],
    obtainableBy: "Bosques móveis do Pântano da Névoa", spriteIndex: 13,
  },
  {
    id: "amarok", name: "Amarok", title: "Lobo Solitário da Noite",
    description: "Lobo gigantesco da tradição inuíte que caça sozinho.",
    lore: "Histórias sobre Amarok advertem caçadores imprudentes e contrastam sua caça solitária com a alcateia comum.",
    folklore: { tradition: "Tradições inuítes", origin: "Regiões árticas da América do Norte", sourceNote: "A grafia e os relatos variam entre línguas e comunidades inuítes.", adaptation: "Mantém o lobo gigantesco e solitário; evita misturá-lo a lobisomens europeus." },
    regionId: "runic", element: "nature", traits: ["lobo", "ártico", "solitário"], rarity: "legendary", role: "striker",
    hp: 184, defense: 72, speed: 80, moves: ["Mordida Solitária", "Caçada Polar", "Uivo do Amarok"],
    obtainableBy: "Caçada ritual nas Montanhas Rúnicas", spriteIndex: 14,
  },
  {
    id: "saci-perere", name: "Saci-Pererê", title: "Travesso do Redemoinho",
    description: "Figura de uma perna só e gorro vermelho que viaja em redemoinhos e prega peças.",
    lore: "Esconde objetos, embaraça crinas, assusta viajantes e pode ser capturado, segundo versões populares, por meio de seu redemoinho e gorro.",
    folklore: { tradition: "Folclore brasileiro", origin: "Brasil", sourceNote: "A figura reúne influências indígenas, africanas e europeias e mudou bastante entre registros históricos.", adaptation: "Preserva uma perna, gorro vermelho, cachimbo em versões modernas e domínio do redemoinho." },
    regionId: "roots", element: "storm", traits: ["travesso", "redemoinho", "gorro"], rarity: "rare", role: "skirmisher",
    hp: 104, defense: 34, speed: 98, moves: ["Pulo de Vento", "Nó na Crina", "Redemoinho do Saci"],
    obtainableBy: "Encontro com um redemoinho nas trilhas das Raízes", spriteIndex: 15,
  },
  {
    id: "raiju", name: "Raijū", title: "Besta do Trovão",
    description: "Yōkai associado ao relâmpago, descrito em formas animais como lobo, cão ou felino.",
    lore: "É ligado a Raijin e aos fenômenos das tempestades; relatos populares explicam marcas e danos causados por raios.",
    folklore: { tradition: "Folclore japonês", origin: "Japão", sourceNote: "A forma não é fixa e varia entre compilações e regiões.", adaptation: "Usa uma forma canina feita de nuvens e eletricidade, uma das representações tradicionais." },
    regionId: "runic", element: "storm", traits: ["yōkai", "relâmpago", "canino"], rarity: "rare", role: "striker",
    hp: 116, defense: 42, speed: 94, moves: ["Pata de Raio", "Salto entre Nuvens", "Rugido do Raijū"],
    obtainableBy: "Picos atingidos por relâmpagos nas Montanhas Rúnicas", spriteIndex: 16,
  },
  {
    id: "tengu", name: "Tengu", title: "Habitante dos Ventos da Montanha",
    description: "Ser sobrenatural japonês de montanha, ligado a aves, ventos e artes marciais.",
    lore: "Representações antigas tendem ao aspecto de ave; formas posteriores incluem rosto vermelho e nariz longo.",
    folklore: { tradition: "Folclore e tradição religiosa japonesa", origin: "Japão", sourceNote: "Tengu variam de espíritos perigosos a protetores e mestres, conforme período e narrativa.", adaptation: "Usa a forma alada antiga e evita reduzi-lo à caricatura de nariz longo." },
    regionId: "archipelago", element: "storm", traits: ["montanha", "ave", "marcial"], rarity: "epic", role: "controller",
    hp: 134, defense: 56, speed: 88, moves: ["Leque de Rajada", "Passo da Montanha", "Vendaval do Tengu"],
    obtainableBy: "Templos elevados do Arquipélago dos Espíritos", spriteIndex: 17,
  },
  {
    id: "ziz", name: "Ziz", title: "Ave Imensa dos Céus",
    description: "Ave colossal da tradição judaica cuja envergadura alcança os limites do céu.",
    lore: "Textos e comentários a colocam entre os grandes seres da criação, ao lado de Behemoth e Leviatã.",
    folklore: { tradition: "Mitologia e literatura rabínica judaica", origin: "Oriente Médio", sourceNote: "Descrições enfatizam escala cósmica e domínio do céu, não uma espécie comum de monstro.", adaptation: "Preserva a ave colossal e o papel celeste sem fundi-la com outras aves míticas." },
    regionId: "desert", element: "storm", traits: ["ave", "colossal", "celeste"], rarity: "mythic", role: "guardian",
    hp: 212, defense: 82, speed: 62, moves: ["Bater de Asas", "Sombra do Horizonte", "Céu de Ziz"],
    obtainableBy: "Evento celeste sobre o Deserto dos Reis Esquecidos", eventExclusive: true, spriteIndex: 18,
  },
  {
    id: "simurgh", name: "Simurgh", title: "Ave Sábia da Tradição Persa",
    description: "Ave benevolente e antiquíssima associada à sabedoria, cura e proteção.",
    lore: "Na literatura persa, acolhe Zāl e o auxilia por meio de uma pena; outras tradições a ligam à árvore de todas as sementes.",
    folklore: { tradition: "Mitologia e literatura persa", origin: "Irã e mundo persófono", sourceNote: "A Simurgh atravessa períodos pré-islâmicos e obras como o Shahnameh, com funções que variam.", adaptation: "Preserva a grande ave sábia, as penas protetoras e o vínculo com árvores e cura." },
    regionId: "desert", element: "storm", traits: ["ave", "sabedoria", "cura"], rarity: "legendary", role: "support",
    hp: 176, defense: 70, speed: 78, moves: ["Pena Protetora", "Voo sobre Alborz", "Sabedoria da Simurgh"],
    obtainableBy: "Santuário elevado além do deserto", spriteIndex: 19,
  },
  {
    id: "black-shuck", name: "Black Shuck", title: "Cão Negro de East Anglia",
    description: "Cão espectral de pelagem negra e olhos ou olho em brasa que percorre estradas e costas inglesas.",
    lore: "Alguns relatos o tratam como presságio perigoso; outros, como acompanhante ou protetor de viajantes solitários.",
    folklore: { tradition: "Folclore inglês", origin: "East Anglia, Inglaterra", sourceNote: "O nome e o comportamento variam em narrativas locais de cães negros espectrais.", adaptation: "Mantém porte canino, pelagem negra e olhar luminoso, incluindo sua ambiguidade entre ameaça e guarda." },
    regionId: "eclipse", element: "spirit", traits: ["canino", "espectral", "presságio"], rarity: "rare", role: "guardian",
    hp: 152, defense: 72, speed: 68, moves: ["Passo na Estrada", "Olho em Brasa", "Vigília de Black Shuck"],
    obtainableBy: "Estradas costeiras do Reino do Eclipse", spriteIndex: 20,
  },
  {
    id: "domovoi", name: "Domovoi", title: "Espírito Guardião da Casa",
    description: "Espírito doméstico eslavo que protege a família e o lar quando é respeitado.",
    lore: "Ruídos noturnos, pequenos trabalhos e advertências são atribuídos a ele; abandono ou desrespeito podem torná-lo hostil.",
    folklore: { tradition: "Folclores eslavos", origin: "Europa Oriental e regiões eslavas", sourceNote: "Aparência e costumes variam, muitas vezes associados à lareira, ao celeiro e aos ancestrais da casa.", adaptation: "Preserva pequena estatura, pelos, vínculo ancestral e papel doméstico." },
    regionId: "mist", element: "spirit", traits: ["doméstico", "ancestral", "guardião"], rarity: "uncommon", role: "support",
    hp: 102, defense: 60, speed: 48, moves: ["Ruído no Assoalho", "Cuidado da Lareira", "Aviso do Domovoi"],
    obtainableBy: "Casas cuidadas no Pântano da Névoa", spriteIndex: 21,
  },
  {
    id: "qilin", name: "Qilin", title: "Presságio de Governo Justo",
    description: "Ser auspicioso chinês de corpo ungulado, associado à benevolência e ao surgimento de sábios.",
    lore: "É descrito como tão gentil que evita pisar em seres vivos; sua aparência combina traços animais sem equivaler ao unicórnio europeu.",
    folklore: { tradition: "Mitologia chinesa", origin: "China", sourceNote: "Iconografia e descrições mudaram entre dinastias e regiões do Leste Asiático.", adaptation: "Mantém cascos, escamas, chifres e temperamento benevolente; não o chama de dragão ou unicórnio." },
    regionId: "archipelago", element: "spirit", traits: ["auspicioso", "ungulado", "benevolente"], rarity: "legendary", role: "support",
    hp: 180, defense: 80, speed: 66, moves: ["Passo sem Dano", "Sopro Auspicioso", "Chegada do Qilin"],
    obtainableBy: "Provação de benevolência no arquipélago", spriteIndex: 22,
  },
  {
    id: "banshee", name: "Banshee", title: "Mensageira do Lamento",
    description: "Figura feminina sobrenatural irlandesa cujo lamento anuncia uma morte na família.",
    lore: "Não é simplesmente uma atacante: sua função tradicional é pressagiar e lamentar, aparecendo em formas jovens ou idosas.",
    folklore: { tradition: "Folclore irlandês", origin: "Irlanda", sourceNote: "O nome deriva de bean sí, mulher do povo feérico, e os relatos se ligam a famílias e territórios.", adaptation: "Transforma o lamento em controle de batalha sem apagar seu papel de mensageira." },
    regionId: "eclipse", element: "spirit", traits: ["feérico", "lamento", "presságio"], rarity: "epic", role: "controller",
    hp: 118, defense: 44, speed: 76, moves: ["Sussurro do Sídhe", "Véu do Presságio", "Lamento da Banshee"],
    obtainableBy: "Colinas silenciosas do Reino do Eclipse", spriteIndex: 23,
  },
  {
    id: "carbunclo", name: "Carbunclo", title: "Pequeno Portador de Luz",
    description: "Animal esquivo de relatos sul-americanos, reconhecido por uma pedra ou brilho precioso na cabeça.",
    lore: "Buscadores de tesouro o descrevem como uma luz móvel na noite; persegui-lo pode revelar riqueza ou levar o ganancioso a se perder.",
    folklore: { tradition: "Folclores mineiros sul-americanos", origin: "Região andina e Cone Sul", sourceNote: "Carbunclo ou carbúnculo aparece em relatos com formas animais diferentes, sempre ligado a brilho e tesouro.", adaptation: "Usa um pequeno quadrúpede com gema luminosa e mantém a aparência variável como parte do bestiário." },
    regionId: "runic", element: "spirit", traits: ["luminoso", "tesouro", "esquivo"], rarity: "rare", role: "skirmisher",
    hp: 108, defense: 46, speed: 92, moves: ["Clarão da Gema", "Rastro Precioso", "Tesouro do Carbunclo"],
    obtainableBy: "Minas antigas das Montanhas Rúnicas", spriteIndex: 24,
  },
  {
    id: "matinta-pereira", name: "Matinta Pereira", title: "Assobio da Noite Amazônica",
    description: "Figura encantada anunciada por um assobio agudo durante a noite.",
    lore: "Em narrativas amazônicas, pode assumir forma de ave ou de uma pessoa idosa e cobrar a promessa de tabaco feita para silenciar seu assobio.",
    folklore: { tradition: "Folclore amazônico", origin: "Amazônia, Brasil", sourceNote: "Os relatos variam entre localidades e alternam formas humanas, aviárias e encantadas.", adaptation: "Preserva o assobio, a metamorfose e a promessa; evita fixar uma única aparência como universal." },
    regionId: "roots", element: "spirit", traits: ["metamorfa", "assobio", "noturna"], rarity: "rare", role: "controller",
    hp: 118, defense: 48, speed: 82, moves: ["Assobio Distante", "Promessa da Noite", "Voo da Matinta"], obtainableBy: "Clareira dos Sussurros", spriteIndex: 0, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "cobra-grande", name: "Cobra Grande", title: "Serpente dos Rios Profundos",
    description: "Serpente colossal associada aos rios e às transformações da paisagem amazônica.",
    lore: "Também chamada Boiúna em diferentes narrativas, desloca águas, cria caminhos e inspira cautela nas margens durante a noite.",
    folklore: { tradition: "Folclore amazônico", origin: "Amazônia, Brasil", sourceNote: "Nomes, dimensões e feitos mudam entre comunidades ribeirinhas.", adaptation: "Mantém o vínculo com rios, tamanho extraordinário e presença noturna." },
    regionId: "roots", element: "water", traits: ["serpente", "fluvial", "colossal"], rarity: "epic", role: "guardian",
    hp: 198, defense: 84, speed: 34, moves: ["Cauda de Corrente", "Olhos da Boiúna", "Rio sem Margem"], obtainableBy: "Coração das Raízes", spriteIndex: 1, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "anhanga", name: "Anhangá", title: "Protetor de Olhos de Fogo",
    description: "Presença protetora da mata frequentemente descrita em forma de veado branco.",
    lore: "Relatos de matriz tupi o relacionam à defesa dos animais e ao castigo de caçadores que violam os pactos da floresta.",
    folklore: { tradition: "Tradições indígenas brasileiras registradas historicamente", origin: "Brasil", sourceNote: "Grafias e interpretações variam, e nem toda tradição o descreve da mesma maneira.", adaptation: "Usa a forma de cervo branco e olhos luminosos como uma representação, não como definição única." },
    regionId: "roots", element: "nature", traits: ["cervo", "guardião", "luminoso"], rarity: "legendary", role: "support",
    hp: 174, defense: 80, speed: 76, moves: ["Passo Branco", "Olhar Protetor", "Pacto de Anhangá"], obtainableBy: "Ruínas da Guardiã", spriteIndex: 2, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "comadre-fulozinha", name: "Comadre Fulozinha", title: "Guardiã dos Cabelos Longos",
    description: "Encantada da mata nordestina que protege animais e desorienta quem desrespeita seu território.",
    lore: "Seu assobio, seus cabelos e a oferta de fumo aparecem em narrativas do Nordeste brasileiro, com muitas formas locais.",
    folklore: { tradition: "Folclore do Nordeste brasileiro", origin: "Nordeste do Brasil", sourceNote: "Características variam por estado e tradição oral.", adaptation: "Preserva o papel guardião, o assobio e os longos cabelos sem misturá-la à Caipora." },
    regionId: "roots", element: "nature", traits: ["encantada", "guardiã", "assobio"], rarity: "rare", role: "skirmisher",
    hp: 124, defense: 52, speed: 90, moves: ["Trança da Mata", "Assobio Cruzado", "Caminho de Fulozinha"], obtainableBy: "Trilha Invertida", spriteIndex: 3, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "uirapuru-encantado", name: "Uirapuru Encantado", title: "Canto que Silencia a Floresta",
    description: "Ave de canto extraordinário cercada por narrativas de encanto, sorte e transformação.",
    lore: "Histórias amazônicas explicam seu canto raro por amores, metamorfoses e promessas, em versões que mudam de narrador para narrador.",
    folklore: { tradition: "Narrativas amazônicas", origin: "Amazônia, Brasil", sourceNote: "O pássaro real e as narrativas encantadas convivem sem formar uma única versão canônica.", adaptation: "Amplifica o canto como poder de apoio e mantém a pequena forma aviária." },
    regionId: "roots", element: "storm", traits: ["ave", "canto", "encantado"], rarity: "uncommon", role: "support",
    hp: 96, defense: 36, speed: 102, moves: ["Canto Raro", "Pausa da Mata", "Voo Encantado"], obtainableBy: "Portal da Mata", spriteIndex: 4, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "umibozu", name: "Umibōzu", title: "Sombra sobre o Mar",
    description: "Aparição marítima gigantesca que surge em águas calmas ou tempestades repentinas.",
    lore: "Marinheiros japoneses contam que a figura escura pode virar embarcações ou exigir um barril, sendo vencida por astúcia em algumas versões.",
    folklore: { tradition: "Folclore marítimo japonês", origin: "Japão", sourceNote: "Forma, tamanho e comportamento variam entre regiões costeiras.", adaptation: "Mantém a silhueta escura, a escala marítima e o encontro com navegantes." },
    regionId: "archipelago", element: "water", traits: ["marítimo", "gigante", "aparição"], rarity: "epic", role: "guardian",
    hp: 206, defense: 86, speed: 24, moves: ["Onda Silenciosa", "Pedido do Barril", "Noite sobre o Mar"], obtainableBy: "Abismo dos Espíritos", spriteIndex: 5, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "ningyo", name: "Ningyo", title: "Oráculo das Correntes",
    description: "Ser aquático japonês de aparência variável, frequentemente ligado a presságios.",
    lore: "Registros e contos descrevem combinações entre peixe e traços humanos; capturá-lo pode anunciar desastres ou longevidade em narrativas distintas.",
    folklore: { tradition: "Folclore japonês", origin: "Japão", sourceNote: "Não equivale à sereia europeia e possui iconografias variadas.", adaptation: "Preserva a forma híbrida aquática e o papel de presságio." },
    regionId: "archipelago", element: "water", traits: ["aquático", "oráculo", "presságio"], rarity: "rare", role: "support",
    hp: 120, defense: 52, speed: 78, moves: ["Escama Oracular", "Voz da Corrente", "Maré do Presságio"], obtainableBy: "Templo das Marés", spriteIndex: 6, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "selkie", name: "Selkie", title: "Viajante da Pele de Foca",
    description: "Ser capaz de deixar a pele de foca para assumir forma humana em terra.",
    lore: "Baladas e contos do Atlântico Norte narram amores e cativeiros ligados ao esconderijo da pele que permite seu retorno ao mar.",
    folklore: { tradition: "Folclores escocês e das ilhas do Atlântico Norte", origin: "Escócia, Orkney e Shetland", sourceNote: "O tom varia entre romance, perda e advertência.", adaptation: "Mantém a pele de foca como centro da metamorfose e evita tratá-la como sereia." },
    regionId: "archipelago", element: "spirit", traits: ["foca", "metamorfa", "marítima"], rarity: "rare", role: "skirmisher",
    hp: 126, defense: 48, speed: 88, moves: ["Pele Guardada", "Passo na Praia", "Retorno às Ondas"], obtainableBy: "Ilhas das Promessas", spriteIndex: 7, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "bake-kujira", name: "Bake-kujira", title: "Esqueleto da Baleia Fantasma",
    description: "Esqueleto espectral de baleia que atravessa o mar acompanhado por aves e peixes incomuns.",
    lore: "Uma narrativa associada à costa de Shimane descreve pescadores encontrando a aparição e os infortúnios que seguiram sua aproximação.",
    folklore: { tradition: "Folclore japonês", origin: "Shimane, Japão", sourceNote: "É uma narrativa regional moderna em comparação com yōkai muito antigos.", adaptation: "Mantém a baleia esquelética, o cortejo animal e o caráter de aparição." },
    regionId: "archipelago", element: "spirit", traits: ["baleia", "esquelético", "fantasma"], rarity: "legendary", role: "controller",
    hp: 188, defense: 72, speed: 40, moves: ["Canto Oco", "Cortejo do Mar", "Maré Fantasma"], obtainableBy: "Recife Ancestral", spriteIndex: 8, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "nokk", name: "Nøkk", title: "Cavalo das Águas Escuras",
    description: "Espírito aquático metamórfico que pode surgir como cavalo junto a rios e lagos.",
    lore: "Tradições escandinavas narram encontros perigosos, música e mudanças de forma ligadas à água.",
    folklore: { tradition: "Folclores escandinavos", origin: "Escandinávia", sourceNote: "Nomes e formas variam entre línguas e regiões nórdicas.", adaptation: "Usa a forma equina aquática e mantém sua natureza metamórfica." },
    regionId: "archipelago", element: "water", traits: ["equino", "metamorfo", "lacustre"], rarity: "epic", role: "controller",
    hp: 148, defense: 62, speed: 84, moves: ["Galope Submerso", "Canção da Margem", "Forma do Nøkk"], obtainableBy: "Cais Cartógrafo", spriteIndex: 9, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "thunderbird", name: "Pássaro do Trovão", title: "Asas que Chamam a Tempestade",
    description: "Grande ser aviário associado ao trovão e aos relâmpagos em diversas tradições indígenas norte-americanas.",
    lore: "Não existe uma versão única: nomes, relações e significados pertencem a povos específicos e não devem ser fundidos em uma narrativa genérica.",
    folklore: { tradition: "Tradições de diferentes povos indígenas da América do Norte", origin: "América do Norte", sourceNote: "Esta entrada reconhece a diversidade e não substitui as narrativas próprias de cada povo.", adaptation: "Representa apenas o motivo amplo de ave e tempestade, sem copiar símbolos cerimoniais específicos." },
    regionId: "runic", element: "storm", traits: ["ave", "trovão", "celeste"], rarity: "mythic", role: "striker",
    hp: 190, defense: 70, speed: 90, moves: ["Bater do Trovão", "Olhar de Relâmpago", "Tempestade Celeste"], obtainableBy: "Pico do Trovão", spriteIndex: 10, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "alicanto", name: "Alicanto", title: "Ave dos Veios Minerais",
    description: "Ave noturna chilena cujas penas brilham conforme o metal ou minério de que se alimenta.",
    lore: "Mineiros seguem sua luz para encontrar riqueza, mas a ganância ou uma perseguição descuidada pode conduzir a precipícios.",
    folklore: { tradition: "Folclore mineiro chileno", origin: "Chile", sourceNote: "O brilho e a dieta mineral distinguem versões de ouro e de prata.", adaptation: "Mantém a ave luminosa e sua ligação ambígua com tesouros subterrâneos." },
    regionId: "runic", element: "spirit", traits: ["ave", "minério", "luminoso"], rarity: "rare", role: "support",
    hp: 110, defense: 46, speed: 92, moves: ["Pena Metálica", "Rastro de Prata", "Veio do Alicanto"], obtainableBy: "Mina do Carbunclo", spriteIndex: 11, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "fenghuang", name: "Fenghuang", title: "Ave da Harmonia Imperial",
    description: "Ave auspiciosa chinesa associada à harmonia, virtude e renovação da ordem.",
    lore: "Sua iconografia reúne traços simbólicos de diferentes aves e se desenvolveu por muitos períodos da história chinesa.",
    folklore: { tradition: "Mitologia e iconografia chinesa", origin: "China", sourceNote: "Não é simplesmente uma fênix ocidental; sua história e seus significados são próprios.", adaptation: "Preserva a ave composta, a dignidade e a associação à harmonia." },
    regionId: "runic", element: "fire", traits: ["ave", "auspicioso", "harmonia"], rarity: "legendary", role: "support",
    hp: 168, defense: 66, speed: 82, moves: ["Pluma das Virtudes", "Dança dos Ventos", "Harmonia do Fenghuang"], obtainableBy: "Santuário do Céu", spriteIndex: 12, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "yeti", name: "Yeti", title: "Habitante das Alturas Nevadas",
    description: "Ser misterioso associado às montanhas e neves do Himalaia.",
    lore: "Relatos locais, traduções e explorações estrangeiras produziram imagens diferentes, nem sempre equivalentes ao popular 'abominável homem das neves'.",
    folklore: { tradition: "Narrativas himalaias", origin: "Região do Himalaia", sourceNote: "Termos e interpretações variam entre comunidades e línguas locais.", adaptation: "Usa uma forma peluda de montanha e evita apresentar especulação moderna como tradição única." },
    regionId: "runic", element: "nature", traits: ["montanha", "peludo", "neve"], rarity: "epic", role: "guardian",
    hp: 210, defense: 90, speed: 30, moves: ["Punho da Geleira", "Passo na Neve", "Eco do Himalaia"], obtainableBy: "Passagem Glacial", spriteIndex: 13, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "ratatoskr", name: "Ratatoskr", title: "Mensageiro da Árvore do Mundo",
    description: "Esquilo que corre pelo tronco de Yggdrasil levando palavras entre a águia e o dragão.",
    lore: "Na Edda em Prosa, suas mensagens alimentam a disputa entre os seres que habitam as extremidades da árvore cósmica.",
    folklore: { tradition: "Mitologia nórdica registrada nas Eddas", origin: "Escandinávia medieval", sourceNote: "A fonte preservada é breve, deixando muitos detalhes visuais em aberto.", adaptation: "Mantém o esquilo mensageiro e a corrida vertical pela árvore do mundo." },
    regionId: "runic", element: "nature", traits: ["esquilo", "mensageiro", "ágil"], rarity: "uncommon", role: "skirmisher",
    hp: 92, defense: 32, speed: 108, moves: ["Recado Afiado", "Corrida no Tronco", "Rumor de Yggdrasil"], obtainableBy: "Ponte Rúnica", spriteIndex: 14, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "kikimora", name: "Kikimora", title: "Presença Atrás do Fogão",
    description: "Espírito doméstico eslavo associado a ruídos, fiação e presságios dentro da casa.",
    lore: "Pode ajudar uma casa bem cuidada ou perturbar seus moradores, dependendo da tradição e da relação com o lar.",
    folklore: { tradition: "Folclores eslavos", origin: "Europa Oriental", sourceNote: "Há versões domésticas e versões ligadas a pântanos.", adaptation: "Combina pequena figura doméstica e sinais do brejo sem tratá-los como forma universal." },
    regionId: "mist", element: "spirit", traits: ["doméstico", "fiandeira", "presságio"], rarity: "uncommon", role: "controller",
    hp: 98, defense: 52, speed: 70, moves: ["Fio Embaraçado", "Ruído na Parede", "Presságio da Kikimora"], obtainableBy: "Casa da Névoa", spriteIndex: 15, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "rusalka", name: "Rusalka", title: "Espírito das Águas Verdes",
    description: "Figura feminina sobrenatural ligada a rios, lagos, vegetação e períodos do calendário eslavo.",
    lore: "As descrições variam muito por época e região, indo de presenças férteis a aparições perigosas.",
    folklore: { tradition: "Folclores eslavos", origin: "Europa Oriental", sourceNote: "Não corresponde exatamente à sereia marítima ocidental.", adaptation: "Mantém o vínculo com água doce, cabelos e vegetação, reconhecendo sua variedade." },
    regionId: "mist", element: "water", traits: ["água doce", "vegetação", "aparição"], rarity: "rare", role: "controller",
    hp: 116, defense: 46, speed: 78, moves: ["Cabelo de Junco", "Canto do Lago", "Dança da Rusalka"], obtainableBy: "Charco dos Ecos", spriteIndex: 16, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "puca", name: "Púca", title: "Metamorfo dos Caminhos",
    description: "Ser do folclore irlandês que assume várias formas animais, frequentemente a de um cavalo escuro.",
    lore: "Pode assustar, aconselhar ou levar viajantes a corridas imprevisíveis, conforme a narrativa.",
    folklore: { tradition: "Folclore irlandês", origin: "Irlanda", sourceNote: "Grafia, temperamento e formas mudam entre regiões e traduções.", adaptation: "Usa a forma equina negra como uma dentre várias possibilidades." },
    regionId: "mist", element: "spirit", traits: ["metamorfo", "equino", "travesso"], rarity: "epic", role: "skirmisher",
    hp: 142, defense: 54, speed: 96, moves: ["Salto do Caminho", "Forma Imprevista", "Corrida do Púca"], obtainableBy: "Bosque Móvel", spriteIndex: 17, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "dullahan", name: "Dullahan", title: "Cavaleiro sem Cabeça",
    description: "Cavaleiro sobrenatural irlandês que carrega a própria cabeça e anuncia a morte.",
    lore: "Quando interrompe sua cavalgada e pronuncia um nome, o destino anunciado se cumpre em muitos relatos.",
    folklore: { tradition: "Folclore irlandês", origin: "Irlanda", sourceNote: "Detalhes sobre montaria, carruagem e objetos carregados variam.", adaptation: "Mantém a cabeça carregada, o cavalo e o papel de mensageiro fatal." },
    regionId: "mist", element: "spirit", traits: ["cavaleiro", "sem cabeça", "presságio"], rarity: "legendary", role: "striker",
    hp: 178, defense: 70, speed: 86, moves: ["Rédea Sombria", "Nome Derradeiro", "Cavalgada do Dullahan"], obtainableBy: "Vila Afundada", spriteIndex: 18, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "fogo-fatuo", name: "Fogo-fátuo", title: "Luz que Desvia Viajantes",
    description: "Luz errante vista sobre pântanos e caminhos, cercada por explicações naturais e narrativas sobrenaturais.",
    lore: "Muitas culturas descrevem luzes que afastam viajantes da estrada ou marcam lugares de memória e perigo.",
    folklore: { tradition: "Folclores europeus e narrativas difundidas globalmente", origin: "Múltiplas regiões", sourceNote: "Nomes e interpretações locais não são equivalentes entre si.", adaptation: "Transforma o motivo da luz errante em criatura sem atribuir uma origem única." },
    regionId: "mist", element: "fire", traits: ["luz", "errante", "pântano"], rarity: "common", role: "skirmisher",
    hp: 82, defense: 28, speed: 112, moves: ["Faísca Errante", "Desvio da Trilha", "Brilho do Brejo"], obtainableBy: "Margem Enevoada", spriteIndex: 19, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "ammit", name: "Ammit", title: "Devoradora dos Corações",
    description: "Ser funerário egípcio com partes de crocodilo, leão e hipopótamo.",
    lore: "Permanece junto à pesagem do coração e devora aquele considerado indigno, impedindo sua continuidade no além.",
    folklore: { tradition: "Religião e mitologia do Egito Antigo", origin: "Egito Antigo", sourceNote: "Sua função é ligada ao julgamento funerário, não à caça aleatória.", adaptation: "Preserva a anatomia composta e o papel de consequência do julgamento." },
    regionId: "desert", element: "nature", traits: ["composto", "julgamento", "funerário"], rarity: "legendary", role: "guardian",
    hp: 218, defense: 92, speed: 32, moves: ["Mandíbula do Julgamento", "Peso do Coração", "Sentença de Ammit"], obtainableBy: "Tumba dos Reis", spriteIndex: 20, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "manticora", name: "Manticora", title: "Predadora dos Relatos Persas",
    description: "Criatura descrita por autores antigos com corpo leonino, rosto humano e cauda perigosa.",
    lore: "Relatos gregos sobre a Pérsia transmitiram e transformaram sua imagem, que depois entrou em bestiários europeus.",
    folklore: { tradition: "Relatos antigos e bestiários medievais", origin: "Pérsia em fontes gregas", sourceNote: "A transmissão histórica produziu variações importantes de anatomia.", adaptation: "Usa corpo de leão, face humana estilizada e cauda armada sem declarar uma forma única." },
    regionId: "desert", element: "fire", traits: ["leonino", "cauda", "bestiário"], rarity: "epic", role: "striker",
    hp: 166, defense: 62, speed: 80, moves: ["Cauda de Espinhos", "Salto Leonino", "Rugido da Manticora"], obtainableBy: "Ossário Colossal", spriteIndex: 21, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "esfinge", name: "Esfinge", title: "Guardiã dos Limiares Sagrados",
    description: "Ser leonino de cabeça humana associado à proteção monumental e à autoridade régia no Egito Antigo.",
    lore: "A esfinge egípcia e a esfinge grega possuem histórias distintas; esta entrada segue o motivo guardião egípcio.",
    folklore: { tradition: "Iconografia e religião do Egito Antigo", origin: "Egito Antigo", sourceNote: "Não funde o guardião egípcio com o enigma da tradição grega.", adaptation: "Mantém corpo de leão, cabeça humana e função protetora." },
    regionId: "desert", element: "spirit", traits: ["leonino", "guardião", "monumental"], rarity: "legendary", role: "controller",
    hp: 186, defense: 84, speed: 48, moves: ["Vigília de Pedra", "Palavra Régia", "Limiar da Esfinge"], obtainableBy: "Ruínas do Sol", spriteIndex: 22, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "roc", name: "Roc", title: "Ave que Oculta o Sol",
    description: "Ave gigantesca das narrativas de viagem do mundo árabe e persa.",
    lore: "Histórias difundidas nas Mil e Uma Noites descrevem sua força para erguer animais enormes e sua escala quase inacreditável.",
    folklore: { tradition: "Literatura árabe e persa de viagens maravilhosas", origin: "Oceano Índico imaginado e Oriente Médio", sourceNote: "A grafia Rukh/Roc e os cenários variam entre traduções.", adaptation: "Preserva a ave colossal e a força de voo sem fundi-la com outras aves míticas." },
    regionId: "desert", element: "storm", traits: ["ave", "colossal", "viajante"], rarity: "mythic", role: "guardian",
    hp: 224, defense: 78, speed: 68, moves: ["Garra do Roc", "Sombra do Sol", "Voo do Horizonte"], obtainableBy: "Portão de Areia", spriteIndex: 23, spriteSheet: SECOND_SPRITE_SHEET,
  },
  {
    id: "ifrit", name: "Ifrit", title: "Espírito de Fogo Rebelde",
    description: "Classe poderosa de jinn associada ao fogo e a forças extraordinárias em tradições islâmicas e árabes.",
    lore: "Textos e narrativas posteriores descrevem ifrits com temperamentos e papéis diversos, não como uma espécie uniforme de demônio.",
    folklore: { tradition: "Tradições islâmicas e folclores árabes", origin: "Oriente Médio", sourceNote: "Conceitos religiosos e narrativos variam por fonte e época.", adaptation: "Representa um jinn ígneo poderoso sem reduzir toda a categoria a antagonistas." },
    regionId: "desert", element: "fire", traits: ["jinn", "fogo", "poderoso"], rarity: "epic", role: "striker",
    hp: 156, defense: 58, speed: 84, moves: ["Punho de Brasa", "Vento do Ifrit", "Coluna de Fogo"], obtainableBy: "Oásis Oculto", spriteIndex: 24, spriteSheet: SECOND_SPRITE_SHEET,
  },
];

export const CREATURES: CreatureDefinition[] = seeds.map(({ moves, spriteIndex, spriteSheet = SPRITE_SHEET, ...seed }) => {
  const completeSeed = { ...seed, moves, spriteIndex, spriteSheet } as CreatureSeed;
  return {
    ...seed,
    attacks: attackFactory[seed.element](completeSeed),
    sprite: {
      sheet: spriteSheet,
      column: spriteIndex % SPRITE_COLUMNS,
      row: Math.floor(spriteIndex / SPRITE_COLUMNS),
      columns: SPRITE_COLUMNS,
      rows: SPRITE_ROWS,
    },
  };
});

export const CREATURE_BY_ID = new Map(CREATURES.map((creature) => [creature.id, creature]));

export const STARTER_TEAM_IDS = ["boitata", "iara", "curupira", "saci-perere", "black-shuck", "boto-cor-de-rosa"] as const;
export const NPC_TEAM_IDS = ["mula-sem-cabeca", "kappa", "mapinguari", "raiju", "domovoi", "qilin"] as const;
