import type { RegionDefinition } from "../types";

export const REGIONS: RegionDefinition[] = [
  { id: "roots", name: "Floresta das Raízes Antigas", subtitle: "Matas guardadas por pactos e rastros invertidos", inspiration: "Folclores florestais brasileiros e sul-americanos", recommendedLevel: "1–12", discovered: 6, totalCreatures: 24, status: "open", mapPosition: { x: 22, y: 50 }, neighbors: ["archipelago", "runic", "mist"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#5be29a", viewport: { x: 18, y: 56, scale: 2.15 }, areas: [
    { id: "roots-gate", name: "Portal da Mata", subtitle: "O primeiro marco dos cartógrafos.", recommendedLevel: "1–3", position: { x: 22, y: 77 }, activity: "explore" },
    { id: "roots-inverted", name: "Trilha Invertida", subtitle: "Pegadas apontam para o caminho errado.", recommendedLevel: "3–5", position: { x: 39, y: 62 }, activity: "wild", unlockAfter: "roots-gate" },
    { id: "roots-whispers", name: "Clareira dos Sussurros", subtitle: "Vozes antigas atravessam as copas.", recommendedLevel: "5–7", position: { x: 57, y: 48 }, activity: "npc", unlockAfter: "roots-inverted" },
    { id: "roots-ruins", name: "Ruínas da Guardiã", subtitle: "Pedras cobertas por símbolos de proteção.", recommendedLevel: "7–9", position: { x: 70, y: 30 }, activity: "sanctuary", unlockAfter: "roots-whispers" },
    { id: "roots-heart", name: "Coração das Raízes", subtitle: "O domínio vivo da guardiã da floresta.", recommendedLevel: "10–12", position: { x: 84, y: 17 }, activity: "boss", unlockAfter: "roots-ruins" },
  ] },
  { id: "archipelago", name: "Arquipélago dos Espíritos", subtitle: "Templos, rios, marés e promessas antigas", inspiration: "Narrativas costeiras, amazônicas e do Leste Asiático", recommendedLevel: "8–20", discovered: 4, totalCreatures: 28, status: "open", mapPosition: { x: 50, y: 75 }, neighbors: ["roots", "deep-sea"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#55d4ff", viewport: { x: 52, y: 78, scale: 2.05 }, areas: [
    { id: "archipelago-dock", name: "Cais Cartógrafo", subtitle: "Barcos de madeira ligam as ilhas.", recommendedLevel: "8–10", position: { x: 19, y: 72 }, activity: "explore" },
    { id: "archipelago-promises", name: "Ilhas das Promessas", subtitle: "Oferendas protegem quem cruza as águas.", recommendedLevel: "10–12", position: { x: 36, y: 57 }, activity: "wild", unlockAfter: "archipelago-dock" },
    { id: "archipelago-tides", name: "Templo das Marés", subtitle: "Sinos respondem ao movimento do oceano.", recommendedLevel: "12–15", position: { x: 53, y: 42 }, activity: "sanctuary", unlockAfter: "archipelago-promises" },
    { id: "archipelago-reef", name: "Recife Ancestral", subtitle: "O recife guarda rotas esquecidas.", recommendedLevel: "15–17", position: { x: 70, y: 31 }, activity: "treasure", unlockAfter: "archipelago-tides" },
    { id: "archipelago-abyss", name: "Abismo dos Espíritos", subtitle: "Uma presença antiga desperta sob as ilhas.", recommendedLevel: "18–20", position: { x: 84, y: 16 }, activity: "boss", unlockAfter: "archipelago-reef" },
  ] },
  { id: "runic", name: "Montanhas Rúnicas", subtitle: "Pedra, vento e trovões sob inscrições antigas", inspiration: "Tradições montanhesas, árticas e centro-asiáticas", recommendedLevel: "15–28", discovered: 3, totalCreatures: 26, status: "open", mapPosition: { x: 48, y: 18 }, neighbors: ["roots", "eclipse"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#ffd45a", viewport: { x: 50, y: 14, scale: 2.2 }, areas: [
    { id: "runic-pass", name: "Passagem Glacial", subtitle: "O gelo revela as primeiras runas.", recommendedLevel: "15–17", position: { x: 18, y: 78 }, activity: "explore" },
    { id: "runic-bridge", name: "Ponte Rúnica", subtitle: "Símbolos brilham a cada travessia.", recommendedLevel: "17–20", position: { x: 35, y: 59 }, activity: "npc", unlockAfter: "runic-pass" },
    { id: "runic-mine", name: "Mina do Carbunclo", subtitle: "Gemas vivas iluminam túneis antigos.", recommendedLevel: "20–22", position: { x: 53, y: 46 }, activity: "treasure", unlockAfter: "runic-bridge" },
    { id: "runic-thunder", name: "Pico do Trovão", subtitle: "Relâmpagos escolhem seus desafiantes.", recommendedLevel: "22–25", position: { x: 70, y: 30 }, activity: "wild", unlockAfter: "runic-mine" },
    { id: "runic-shrine", name: "Santuário do Céu", subtitle: "O guardião espera acima das nuvens.", recommendedLevel: "25–28", position: { x: 84, y: 15 }, activity: "boss", unlockAfter: "runic-thunder" },
  ] },
  { id: "mist", name: "Pântano da Névoa", subtitle: "Casas antigas surgem e somem entre águas rasas", inspiration: "Espíritos domésticos eslavos e lendas de brumas", recommendedLevel: "18–32", discovered: 0, totalCreatures: 22, status: "locked", mapPosition: { x: 52, y: 39 }, neighbors: ["roots", "desert"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#8fceb0", viewport: { x: 52, y: 43, scale: 2.15 }, areas: [
    { id: "mist-bank", name: "Margem Enevoada", subtitle: "O caminho desaparece atrás de cada passo.", recommendedLevel: "18–20", position: { x: 17, y: 77 }, activity: "explore" },
    { id: "mist-village", name: "Vila Afundada", subtitle: "Telhados emergem quando a névoa recua.", recommendedLevel: "20–23", position: { x: 34, y: 60 }, activity: "npc", unlockAfter: "mist-bank" },
    { id: "mist-grove", name: "Bosque Móvel", subtitle: "Árvores trocam de lugar durante a noite.", recommendedLevel: "23–26", position: { x: 52, y: 45 }, activity: "wild", unlockAfter: "mist-village" },
    { id: "mist-echoes", name: "Charco dos Ecos", subtitle: "Chamados distantes atraem os desatentos.", recommendedLevel: "26–29", position: { x: 69, y: 29 }, activity: "treasure", unlockAfter: "mist-grove" },
    { id: "mist-house", name: "Casa da Névoa", subtitle: "A morada muda antes do amanhecer.", recommendedLevel: "29–32", position: { x: 84, y: 16 }, activity: "boss", unlockAfter: "mist-echoes" },
  ] },
  { id: "desert", name: "Deserto dos Reis Esquecidos", subtitle: "O sol vigia câmaras soterradas", inspiration: "Narrativas do norte da África, Mediterrâneo e Oriente Médio", recommendedLevel: "24–38", discovered: 0, totalCreatures: 31, status: "locked", mapPosition: { x: 82, y: 43 }, neighbors: ["mist", "deep-sea", "eclipse"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#ffac5c", viewport: { x: 84, y: 45, scale: 2.15 }, areas: [
    { id: "desert-gate", name: "Portão de Areia", subtitle: "Dunas cobrem uma estrada monumental.", recommendedLevel: "24–27", position: { x: 17, y: 78 }, activity: "explore" },
    { id: "desert-ossuary", name: "Ossário Colossal", subtitle: "Ossos antigos formam arcos sobre a trilha.", recommendedLevel: "27–30", position: { x: 34, y: 59 }, activity: "wild", unlockAfter: "desert-gate" },
    { id: "desert-oasis", name: "Oásis Oculto", subtitle: "Água e sombra recompensam os atentos.", recommendedLevel: "30–33", position: { x: 51, y: 45 }, activity: "treasure", unlockAfter: "desert-ossuary" },
    { id: "desert-sun", name: "Ruínas do Sol", subtitle: "Espelhos de pedra concentram a luz.", recommendedLevel: "33–35", position: { x: 69, y: 30 }, activity: "sanctuary", unlockAfter: "desert-oasis" },
    { id: "desert-tomb", name: "Tumba dos Reis", subtitle: "O último selo aguarda além das colunas.", recommendedLevel: "36–38", position: { x: 84, y: 16 }, activity: "boss", unlockAfter: "desert-sun" },
  ] },
  { id: "deep-sea", name: "Mar das Profundezas", subtitle: "Santuários afundados respiram sob ilhas vivas", inspiration: "Lendas marítimas e cosmologias insulares", recommendedLevel: "32–48", discovered: 0, totalCreatures: 29, status: "locked", mapPosition: { x: 78, y: 77 }, neighbors: ["archipelago", "desert"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#55a8ff" },
  { id: "eclipse", name: "Reino do Eclipse", subtitle: "Uma fronteira entre memória e presságio", inspiration: "Narrativas de seres liminares, ancestrais e aparições", recommendedLevel: "40+", discovered: 0, totalCreatures: 34, status: "event", mapPosition: { x: 82, y: 14 }, neighbors: ["runic", "desert"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#b48cff" },
];
