import type { RegionDefinition } from "../types";

export const REGIONS: RegionDefinition[] = [
  { id: "roots", name: "Floresta das Raízes Antigas", subtitle: "Matas guardadas por pactos e rastros invertidos", inspiration: "Folclores florestais brasileiros e sul-americanos", recommendedLevel: "1–12", discovered: 6, totalCreatures: 24, status: "open", mapPosition: { x: 22, y: 50 }, neighbors: ["archipelago", "runic", "mist"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#5be29a" },
  { id: "archipelago", name: "Arquipélago dos Espíritos", subtitle: "Templos, rios, marés e promessas antigas", inspiration: "Narrativas costeiras, amazônicas e do Leste Asiático", recommendedLevel: "8–20", discovered: 4, totalCreatures: 28, status: "open", mapPosition: { x: 50, y: 75 }, neighbors: ["roots", "deep-sea"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#55d4ff" },
  { id: "runic", name: "Montanhas Rúnicas", subtitle: "Pedra, vento e trovões sob inscrições antigas", inspiration: "Tradições montanhesas, árticas e centro-asiáticas", recommendedLevel: "15–28", discovered: 3, totalCreatures: 26, status: "open", mapPosition: { x: 48, y: 18 }, neighbors: ["roots", "eclipse"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#ffd45a" },
  { id: "mist", name: "Pântano da Névoa", subtitle: "Casas antigas surgem e somem entre águas rasas", inspiration: "Espíritos domésticos eslavos e lendas de brumas", recommendedLevel: "18–32", discovered: 0, totalCreatures: 22, status: "locked", mapPosition: { x: 52, y: 39 }, neighbors: ["roots", "desert"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#8fceb0" },
  { id: "desert", name: "Deserto dos Reis Esquecidos", subtitle: "O sol vigia câmaras soterradas", inspiration: "Narrativas do norte da África, Mediterrâneo e Oriente Médio", recommendedLevel: "24–38", discovered: 0, totalCreatures: 31, status: "locked", mapPosition: { x: 82, y: 43 }, neighbors: ["mist", "deep-sea", "eclipse"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#ffac5c" },
  { id: "deep-sea", name: "Mar das Profundezas", subtitle: "Santuários afundados respiram sob ilhas vivas", inspiration: "Lendas marítimas e cosmologias insulares", recommendedLevel: "32–48", discovered: 0, totalCreatures: 29, status: "locked", mapPosition: { x: 78, y: 77 }, neighbors: ["archipelago", "desert"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#55a8ff" },
  { id: "eclipse", name: "Reino do Eclipse", subtitle: "Uma fronteira entre memória e presságio", inspiration: "Narrativas de seres liminares, ancestrais e aparições", recommendedLevel: "40+", discovered: 0, totalCreatures: 34, status: "event", mapPosition: { x: 82, y: 14 }, neighbors: ["runic", "desert"], activities: ["explore", "wild", "npc", "treasure", "sanctuary", "boss"], accent: "#b48cff" },
];
