import type { ArpgAbilityCardDefinition } from "../domain/types";
import { LEGEND_ABILITY_DEFINITIONS } from "./legend-abilities";
import { tuneSignaturePower } from "./legend-balance";

/** Kept unchanged so signed runs and historical battles keep their original rules. */
export const LEGACY_ARPG_ABILITY_CARDS: ArpgAbilityCardDefinition[] = [
  {
    id: "ancestral-roots",
    name: "Raízes Ancestrais",
    creatureId: "curupira",
    rarity: "rare",
    element: "nature",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 6200,
    damage: 28,
    radius: 155,
    durationMs: 1800,
    purchasePrice: null,
    purchasable: false,
    acquisition: { source: "starter", label: "Carta inicial" },
    description: "Raízes explodem no ponto mirado e imobilizam inimigos.",
  },
  {
    id: "boitata-flame",
    name: "Chama do Boitatá",
    creatureId: "boitata",
    rarity: "rare",
    element: "fire",
    kind: "projectile",
    behavior: "piercing-projectile",
    cooldownMs: 4800,
    damage: 44,
    projectileSpeed: 760,
    purchasePrice: null,
    purchasable: false,
    acquisition: { source: "starter", label: "Carta inicial" },
    description: "Uma serpente de fogo atravessa a sala em linha reta.",
  },
  {
    id: "saci-whirlwind",
    name: "Tornado Travesso",
    creatureId: "saci-perere",
    rarity: "uncommon",
    element: "storm",
    kind: "area",
    behavior: "self-area",
    cooldownMs: 5200,
    damage: 34,
    radius: 130,
    durationMs: 1200,
    purchasePrice: 120,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Um redemoinho acompanha o jogador e derruba criaturas próximas.",
  },
  {
    id: "iara-song",
    name: "Canto da Iara",
    creatureId: "iara",
    rarity: "epic",
    element: "water",
    kind: "control",
    behavior: "self-area",
    cooldownMs: 7800,
    damage: 12,
    radius: 190,
    durationMs: 2300,
    purchasePrice: 240,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "O canto interrompe inimigos comuns e abre espaço para reposicionamento.",
  },
  {
    id: "caipora-arrow",
    name: "Flecha da Caipora",
    creatureId: "caipora",
    rarity: "common",
    element: "nature",
    kind: "projectile",
    behavior: "projectile",
    cooldownMs: 3600,
    damage: 32,
    projectileSpeed: 820,
    purchasePrice: 80,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Disparo rápido de caça, simples e eficiente contra alvos isolados.",
  },
  {
    id: "kappa-splash",
    name: "Impacto do Kappa",
    creatureId: "kappa",
    rarity: "common",
    element: "water",
    kind: "area",
    behavior: "self-area",
    cooldownMs: 4200,
    damage: 30,
    radius: 118,
    purchasePrice: 80,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Uma explosão curta de água repele inimigos ao redor do jogador.",
  },
  {
    id: "kelpie-surge",
    name: "Corrente do Kelpie",
    creatureId: "kelpie",
    rarity: "uncommon",
    element: "water",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 5600,
    damage: 26,
    radius: 145,
    durationMs: 1600,
    purchasePrice: 120,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Uma corrente de água prende inimigos no ponto escolhido.",
  },
  {
    id: "tengu-gust",
    name: "Rajada do Tengu",
    creatureId: "tengu",
    rarity: "uncommon",
    element: "storm",
    kind: "area",
    behavior: "self-area",
    cooldownMs: 5000,
    damage: 38,
    radius: 142,
    purchasePrice: 120,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Uma rajada circular abre espaço e pune grupos próximos.",
  },
  {
    id: "banshee-wail",
    name: "Lamento da Banshee",
    creatureId: "banshee",
    rarity: "rare",
    element: "spirit",
    kind: "control",
    behavior: "self-area",
    cooldownMs: 6900,
    damage: 36,
    radius: 175,
    durationMs: 1900,
    purchasePrice: 180,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Um lamento sobrenatural paralisa inimigos próximos por um curto período.",
  },
  {
    id: "medusa-gaze",
    name: "Olhar da Medusa",
    creatureId: "medusa",
    rarity: "legendary",
    element: "spirit",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 9400,
    damage: 58,
    radius: 128,
    durationMs: 2500,
    purchasePrice: 320,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Petrifica e causa alto dano numa zona pequena ao redor do alvo.",
  },
  {
    id: "kraken-grasp",
    name: "Tentáculos do Kraken",
    creatureId: "kraken",
    rarity: "legendary",
    element: "water",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 9800,
    damage: 64,
    radius: 168,
    durationMs: 2800,
    purchasePrice: 320,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Tentáculos emergem no ponto escolhido, prendendo e esmagando alvos.",
  },
  {
    id: "simurgh-renewal",
    name: "Renovação do Simurgh",
    creatureId: "simurgh",
    rarity: "legendary",
    element: "spirit",
    kind: "defense",
    behavior: "renewal",
    cooldownMs: 12000,
    damage: 0,
    restoreHp: 54,
    purchasePrice: 320,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Uma bênção ancestral restaura vida e cria uma janela segura para reposicionar.",
  },
  {
    id: "roc-horizon-storm",
    name: "Tempestade do Horizonte",
    creatureId: "roc",
    rarity: "mythic",
    element: "storm",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 11200,
    damage: 72,
    radius: 188,
    durationMs: 2200,
    purchasePrice: 500,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Uma tempestade colossal cai no ponto mirado, causando alto dano e travando inimigos por alguns instantes.",
  },
];

const legacyCardById = new Map(LEGACY_ARPG_ABILITY_CARDS.map((card) => [card.id, card]));

export const ARPG_ABILITY_CARDS: ArpgAbilityCardDefinition[] = LEGEND_ABILITY_DEFINITIONS.map((definition) => {
  const template = legacyCardById.get(definition.templateId)!;
  return tuneSignaturePower({
    ...template,
    id: definition.id,
    visualEffectId: definition.templateId,
    name: definition.name,
    creatureId: definition.legendId,
    description: definition.description,
    element: definition.element,
    purchasePrice: null,
    purchasable: false,
    acquisition: {
      source: definition.legendId === "curupira" ? "starter" : "legend",
      label: definition.legendId === "curupira" ? "Ataque da Lenda inicial" : "Incluído com esta Lenda",
    },
  }, definition.id);
});

export const STARTER_ARPG_ABILITY_IDS = ["curupira-root-snare", "curupira-ember-arrow"] as const;

export const ARPG_ABILITY_CARD_BY_ID = new Map(
  [...LEGACY_ARPG_ABILITY_CARDS, ...ARPG_ABILITY_CARDS].map((card) => [card.id, card]),
);

/** Accept legacy IDs only when reading already frozen combat/save data. */
export const ARPG_ABILITY_CARD_IDS = new Set(
  ARPG_ABILITY_CARD_BY_ID.keys(),
);
export const CURRENT_ARPG_ABILITY_CARD_IDS = new Set(ARPG_ABILITY_CARDS.map((card) => card.id));

export const STARTER_ARPG_ABILITY_ID_SET = new Set<string>(STARTER_ARPG_ABILITY_IDS);
