import type { ArpgAbilityCardDefinition } from "../domain/types";

/**
 * Additional avatar abilities based on the researched folklore essence roster.
 * Mechanics are limited to the combat behaviors currently implemented by the ARPG.
 */
export const ARPG_FOLKLORE_ABILITY_EXPANSION: ArpgAbilityCardDefinition[] = [
  {
    id: "boto-river-current",
    name: "Corrente do Boto",
    creatureId: "boto-cor-de-rosa",
    rarity: "uncommon",
    element: "water",
    kind: "projectile",
    behavior: "projectile",
    cooldownMs: 5100,
    damage: 34,
    projectileSpeed: 780,
    purchasePrice: 120,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do Boto-cor-de-rosa: o avatar lança uma corrente fluvial em linha reta.",
  },
  {
    id: "cuca-echo-cauldron",
    name: "Caldeirão de Eco",
    creatureId: "cuca",
    rarity: "rare",
    element: "spirit",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 7200,
    damage: 40,
    radius: 148,
    durationMs: 1800,
    purchasePrice: 180,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência da Cuca: o avatar detona um caldeirão de ecos no ponto mirado e enraíza inimigos próximos.",
  },
  {
    id: "mula-cinder-stampede",
    name: "Estouro de Cinzas",
    creatureId: "mula-sem-cabeca",
    rarity: "uncommon",
    element: "fire",
    kind: "area",
    behavior: "self-area",
    cooldownMs: 5600,
    damage: 42,
    radius: 138,
    purchasePrice: 120,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência da Mula sem Cabeça: o avatar libera um anel de brasas ao redor de si.",
  },
  {
    id: "matinta-whistling-mark",
    name: "Assobio da Matinta",
    creatureId: "matinta-pereira",
    rarity: "common",
    element: "spirit",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 4800,
    damage: 26,
    radius: 125,
    durationMs: 1300,
    purchasePrice: 80,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência da Matinta Pereira: um assobio do avatar atinge o ponto mirado e prende os inimigos próximos.",
  },
  {
    id: "boiuna-eddy-snare",
    name: "Remanso da Boiúna",
    creatureId: "boiuna",
    rarity: "epic",
    element: "water",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 9200,
    damage: 58,
    radius: 178,
    durationMs: 2300,
    purchasePrice: 240,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência da Cobra Grande: o avatar abre um remanso no ponto mirado e enraíza quem fica na corrente.",
  },
  {
    id: "mapinguari-hollow-roar",
    name: "Rugido Oco",
    creatureId: "mapinguari",
    rarity: "legendary",
    element: "nature",
    kind: "control",
    behavior: "self-area",
    cooldownMs: 10400,
    damage: 66,
    radius: 190,
    durationMs: 2400,
    purchasePrice: 320,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do Mapinguari: o avatar emite um rugido subterrâneo que atinge e prende inimigos próximos.",
  },
  {
    id: "vitoria-regia-moon-bloom",
    name: "Flor de Luar",
    creatureId: "vitoria-regia",
    rarity: "uncommon",
    element: "water",
    kind: "defense",
    behavior: "renewal",
    cooldownMs: 7200,
    damage: 0,
    restoreHp: 38,
    purchasePrice: 120,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência da Vitória-Régia: o avatar recupera vida sob o brilho de uma flor-d'água.",
  },
  {
    id: "alicanto-mineral-glint",
    name: "Brilho Mineral",
    creatureId: "alicanto",
    rarity: "rare",
    element: "storm",
    kind: "projectile",
    behavior: "piercing-projectile",
    cooldownMs: 7500,
    damage: 48,
    projectileSpeed: 780,
    purchasePrice: 180,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do Alicanto: o avatar dispara um clarão metálico que atravessa inimigos em linha reta.",
  },
  {
    id: "camahueto-hoofbreak",
    name: "Rompente de Cascos",
    creatureId: "camahueto",
    rarity: "epic",
    element: "water",
    kind: "control",
    behavior: "self-area",
    cooldownMs: 8900,
    damage: 58,
    radius: 176,
    durationMs: 2100,
    purchasePrice: 240,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do Camahueto: o avatar golpeia o solo com força de maré e prende criaturas ao redor.",
  },
  {
    id: "ahuizotl-spring-hand",
    name: "Mão da Nascente",
    creatureId: "ahuizotl",
    rarity: "legendary",
    element: "water",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 10800,
    damage: 70,
    radius: 184,
    durationMs: 2600,
    purchasePrice: 320,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do Ahuízotl: uma nascente invocada pelo avatar irrompe no ponto mirado e segura os inimigos.",
  },
  {
    id: "llorona-river-lament",
    name: "Lamento da Margem",
    creatureId: "la-llorona",
    rarity: "epic",
    element: "spirit",
    kind: "control",
    behavior: "self-area",
    cooldownMs: 8800,
    damage: 48,
    radius: 178,
    durationMs: 2300,
    purchasePrice: 240,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência de La Llorona: o avatar solta uma onda de ecos que atinge e enraíza quem estiver perto.",
  },
  {
    id: "cadejo-crossroads-pulse",
    name: "Pulso da Encruzilhada",
    creatureId: "cadejo",
    rarity: "common",
    element: "spirit",
    kind: "control",
    behavior: "self-area",
    cooldownMs: 4900,
    damage: 30,
    radius: 126,
    durationMs: 1100,
    purchasePrice: 80,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do Cadejo: o avatar libera um latido espectral que atinge e prende adversários próximos.",
  },
  {
    id: "chupacabra-night-quills",
    name: "Farpas da Sombra",
    creatureId: "chupacabra",
    rarity: "common",
    element: "spirit",
    kind: "projectile",
    behavior: "projectile",
    cooldownMs: 4200,
    damage: 35,
    projectileSpeed: 830,
    purchasePrice: 80,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do Chupacabra: o avatar lança uma farpa noturna veloz contra um alvo em linha.",
  },
  {
    id: "jackalope-bramble-bounce",
    name: "Espinho de Galhada",
    creatureId: "jackalope",
    rarity: "common",
    element: "nature",
    kind: "projectile",
    behavior: "piercing-projectile",
    cooldownMs: 4600,
    damage: 26,
    projectileSpeed: 790,
    purchasePrice: 80,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do Jackalope: o avatar arremessa um espinho de pradaria que atravessa alvos alinhados.",
  },
  {
    id: "jersey-devil-pine-scream",
    name: "Grito dos Pinheiros",
    creatureId: "jersey-devil",
    rarity: "uncommon",
    element: "storm",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 6300,
    damage: 42,
    radius: 150,
    durationMs: 1650,
    purchasePrice: 120,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do Jersey Devil: um grito do avatar atravessa a clareira mirado e prende inimigos atingidos.",
  },
  {
    id: "selkie-breaker-lance",
    name: "Lança de Arrebentação",
    creatureId: "selkie",
    rarity: "rare",
    element: "water",
    kind: "projectile",
    behavior: "piercing-projectile",
    cooldownMs: 7000,
    damage: 46,
    projectileSpeed: 760,
    purchasePrice: 180,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência da selkie: o avatar lança uma onda estreita que corta uma linha de inimigos.",
  },
  {
    id: "black-shuck-lantern-gaze",
    name: "Olhar de Lanterna",
    creatureId: "black-shuck",
    rarity: "epic",
    element: "spirit",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 8500,
    damage: 54,
    radius: 162,
    durationMs: 1900,
    purchasePrice: 240,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do Black Shuck: o avatar projeta um clarão espectral que atinge e prende alvos no ponto mirado.",
  },
  {
    id: "baba-yaga-threshold-fence",
    name: "Cerca do Limiar",
    creatureId: "baba-yaga",
    rarity: "legendary",
    element: "nature",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 10600,
    damage: 68,
    radius: 185,
    durationMs: 2600,
    purchasePrice: 320,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência de Baba Yaga: raízes erguidas pelo avatar fecham o ponto mirado e prendem quem estiver ali.",
  },
  {
    id: "leshy-forest-circle",
    name: "Limite da Floresta",
    creatureId: "leshy",
    rarity: "uncommon",
    element: "nature",
    kind: "control",
    behavior: "self-area",
    cooldownMs: 6100,
    damage: 38,
    radius: 148,
    durationMs: 1800,
    purchasePrice: 120,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do leshy: o avatar marca um círculo de raízes que atinge e prende quem se aproxima.",
  },
  {
    id: "anansi-thread-snare",
    name: "Fio de Anansi",
    creatureId: "anansi",
    rarity: "rare",
    element: "spirit",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 7200,
    damage: 44,
    radius: 140,
    durationMs: 1750,
    purchasePrice: 180,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência de Anansi: o avatar tece uma armadilha no ponto mirado que atinge e prende inimigos próximos.",
  },
  {
    id: "sasabonsam-canopy-strike",
    name: "Braço de Galho",
    creatureId: "sasabonsam",
    rarity: "epic",
    element: "nature",
    kind: "projectile",
    behavior: "piercing-projectile",
    cooldownMs: 8400,
    damage: 52,
    projectileSpeed: 720,
    purchasePrice: null,
    purchasable: false,
    acquisition: { source: "lobby-shop", label: "Aguardando revisão cultural" },
    description: "Essência de Sasabonsam: um galho invocado pelo avatar golpeia em linha e atravessa inimigos.",
  },
  {
    id: "impundulu-thunderclap",
    name: "Bater de Asas",
    creatureId: "impundulu",
    rarity: "epic",
    element: "storm",
    kind: "control",
    behavior: "self-area",
    cooldownMs: 9400,
    damage: 57,
    radius: 170,
    durationMs: 2100,
    purchasePrice: 240,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do Impundulu: o avatar libera um trovão em círculo que atinge e prende adversários próximos.",
  },
  {
    id: "tokoloshe-low-mist",
    name: "Armadilha Baixa",
    creatureId: "tokoloshe",
    rarity: "uncommon",
    element: "spirit",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 6200,
    damage: 38,
    radius: 136,
    durationMs: 1500,
    purchasePrice: 120,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência tokoloshe: uma armadilha de névoa do avatar se fecha no ponto mirado e prende alvos próximos.",
  },
  {
    id: "oni-kanabo-impact",
    name: "Golpe de Kanabō",
    creatureId: "oni",
    rarity: "rare",
    element: "fire",
    kind: "control",
    behavior: "self-area",
    cooldownMs: 7600,
    damage: 48,
    radius: 158,
    durationMs: 1800,
    purchasePrice: 180,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do oni: o avatar concentra um impacto de fogo no solo que atinge e prende quem estiver perto.",
  },
  {
    id: "jiangshi-paper-seal",
    name: "Selo de Papel",
    creatureId: "jiangshi",
    rarity: "rare",
    element: "spirit",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 7800,
    damage: 46,
    radius: 150,
    durationMs: 2100,
    purchasePrice: 180,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do jiangshi: o avatar lança um selo espectral no ponto mirado e prende alvos próximos.",
  },
  {
    id: "huli-jing-foxfire",
    name: "Fogo-Raposa",
    creatureId: "huli-jing",
    rarity: "epic",
    element: "spirit",
    kind: "projectile",
    behavior: "projectile",
    cooldownMs: 8200,
    damage: 56,
    projectileSpeed: 740,
    purchasePrice: 240,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência de huli jing: o avatar guia uma chama espiritual em linha contra um alvo.",
  },
  {
    id: "tikbalang-hoofbeat",
    name: "Batida de Casco",
    creatureId: "tikbalang",
    rarity: "common",
    element: "nature",
    kind: "control",
    behavior: "self-area",
    cooldownMs: 4300,
    damage: 30,
    radius: 120,
    durationMs: 1100,
    purchasePrice: 80,
    purchasable: true,
    acquisition: { source: "lobby-shop", label: "Loja do lobby" },
    description: "Essência do tikbalang: o avatar golpeia o chão com um pulso que atinge e prende criaturas próximas.",
  },
  {
    id: "manananggal-shadow-sweep",
    name: "Varredura de Sombra",
    creatureId: "manananggal",
    rarity: "rare",
    element: "spirit",
    kind: "projectile",
    behavior: "piercing-projectile",
    cooldownMs: 7700,
    damage: 48,
    projectileSpeed: 760,
    purchasePrice: null,
    purchasable: false,
    acquisition: { source: "lobby-shop", label: "Aguardando revisão cultural" },
    description: "Essência da manananggal: o avatar envia um arco abstrato de sombra que atravessa alvos alinhados.",
  },
  {
    id: "penanggalan-return-tether",
    name: "Fio de Retorno",
    creatureId: "penanggalan",
    rarity: "rare",
    element: "spirit",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 7900,
    damage: 44,
    radius: 146,
    durationMs: 1800,
    purchasePrice: null,
    purchasable: false,
    acquisition: { source: "lobby-shop", label: "Aguardando revisão cultural" },
    description: "Essência da penanggalan: um fio de sombra lançado pelo avatar atinge e prende inimigos no ponto mirado.",
  },
  {
    id: "bunyip-billabong-echo",
    name: "Eco do Billabong",
    creatureId: "bunyip",
    rarity: "uncommon",
    element: "water",
    kind: "control",
    behavior: "self-area",
    cooldownMs: 6300,
    damage: 36,
    radius: 150,
    durationMs: 1500,
    purchasePrice: null,
    purchasable: false,
    acquisition: { source: "lobby-shop", label: "Aguardando revisão cultural" },
    description: "Essência do bunyip: o avatar emite um eco de poço d'água que atinge e prende quem estiver por perto.",
  },
  {
    id: "taniwha-place-ward",
    name: "Corrente do Lugar",
    creatureId: "taniwha",
    rarity: "legendary",
    element: "water",
    kind: "control",
    behavior: "targeted-control",
    cooldownMs: 11000,
    damage: 64,
    radius: 190,
    durationMs: 2800,
    purchasePrice: null,
    purchasable: false,
    acquisition: { source: "lobby-shop", label: "Aguardando revisão cultural" },
    description: "Essência de taniwha: o avatar convoca uma barreira d'água no ponto mirado que atinge e prende inimigos.",
  },
];
