-- Mythic Saturday Raids: configurable event + lobby + authoritative room state + idempotent rewards.

create table public.raid_events (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  boss_creature_id text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  presentation_timezone text not null default 'America/Sao_Paulo',
  min_players integer not null default 2 check (min_players between 2 and 5),
  max_players integer not null default 5 check (max_players between 2 and 5 and max_players >= min_players),
  recommended_level integer not null default 1 check (recommended_level >= 1),
  boss_config jsonb not null default '{}'::jsonb,
  rewards jsonb not null default '{}'::jsonb,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table public.raid_rooms (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.raid_events(id) on delete cascade,
  host_id uuid not null references public.profiles(id) on delete cascade,
  invite_code text not null unique,
  status text not null default 'lobby'
    check (status in ('lobby', 'active', 'victory', 'defeat', 'closed')),
  state jsonb,
  version integer not null default 0 check (version >= 0),
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz
);

create table public.raid_participants (
  room_id uuid not null references public.raid_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  seat integer not null check (seat between 1 and 5),
  team_snapshot jsonb not null,
  is_ready boolean not null default false,
  presence_status text not null default 'online'
    check (presence_status in ('online', 'loading', 'ready', 'disconnected', 'reconnecting', 'spectator')),
  contribution jsonb not null default '{"actions":0,"damage":0,"healing":0,"shield":0,"buffs":0,"debuffs":0,"terrain":0}'::jsonb,
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (room_id, user_id),
  unique (room_id, seat)
);

create table public.raid_actions (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.raid_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  client_action_id uuid not null,
  action_type text not null,
  payload jsonb not null default '{}'::jsonb,
  result jsonb,
  created_at timestamptz not null default now(),
  unique (room_id, user_id, client_action_id)
);

create table public.raid_room_events (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.raid_rooms(id) on delete cascade,
  sequence integer not null,
  event_type text not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  unique (room_id, sequence)
);

create table public.raid_reward_ledger (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.raid_events(id) on delete cascade,
  room_id uuid not null references public.raid_rooms(id) on delete cascade,
  player_id uuid not null references public.profiles(id) on delete cascade,
  reward_id text not null,
  reward_type text not null,
  creature_card_id text,
  granted_at timestamptz not null default now(),
  unique (event_id, player_id, reward_type)
);

create index raid_events_schedule_idx on public.raid_events (starts_at, ends_at) where is_published;
create index raid_rooms_event_status_idx on public.raid_rooms (event_id, status, created_at desc);
create index raid_participants_user_idx on public.raid_participants (user_id, joined_at desc);
create index raid_room_events_room_idx on public.raid_room_events (room_id, sequence);

alter table public.raid_events enable row level security;
alter table public.raid_rooms enable row level security;
alter table public.raid_participants enable row level security;
alter table public.raid_actions enable row level security;
alter table public.raid_room_events enable row level security;
alter table public.raid_reward_ledger enable row level security;

create or replace function private.is_raid_participant(target_room_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.raid_participants
    where room_id = target_room_id and user_id = auth.uid()
  );
$$;

revoke all on function private.is_raid_participant(uuid) from public, anon;
grant execute on function private.is_raid_participant(uuid) to authenticated, service_role;

create policy "published raid events are readable"
on public.raid_events for select to authenticated
using (is_published);

create policy "raid participants read rooms"
on public.raid_rooms for select to authenticated
using (private.is_raid_participant(id));

create policy "raid participants read participants"
on public.raid_participants for select to authenticated
using (private.is_raid_participant(room_id));

create policy "raid participants read room events"
on public.raid_room_events for select to authenticated
using (private.is_raid_participant(room_id));

create policy "players read own raid rewards"
on public.raid_reward_ledger for select to authenticated
using (player_id = auth.uid());

revoke all on public.raid_events, public.raid_rooms, public.raid_participants,
  public.raid_actions, public.raid_room_events, public.raid_reward_ledger
from public, anon, authenticated;

grant select on public.raid_events to authenticated;
grant select on public.raid_rooms, public.raid_participants, public.raid_room_events,
  public.raid_reward_ledger to authenticated;
grant all privileges on public.raid_events, public.raid_rooms, public.raid_participants,
  public.raid_actions, public.raid_room_events, public.raid_reward_ledger to service_role;
grant usage, select on sequence public.raid_actions_id_seq to service_role;
grant usage, select on sequence public.raid_room_events_id_seq to service_role;

create or replace function public.get_raid_schedule()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', events.id,
    'slug', events.slug,
    'title', events.title,
    'bossCreatureId', events.boss_creature_id,
    'startsAt', events.starts_at,
    'endsAt', events.ends_at,
    'presentationTimezone', events.presentation_timezone,
    'minPlayers', events.min_players,
    'maxPlayers', events.max_players,
    'recommendedLevel', events.recommended_level,
    'bossConfig', events.boss_config,
    'rewards', events.rewards,
    'serverNow', now(),
    'status', case
      when now() < events.starts_at then 'upcoming'
      when now() < events.ends_at then 'active'
      else 'ended'
    end
  ) order by events.starts_at), '[]'::jsonb)
  from public.raid_events events
  where events.is_published
    and events.ends_at >= now() - interval '7 days'
    and events.starts_at <= now() + interval '35 days';
$$;

revoke all on function public.get_raid_schedule() from public, anon;
grant execute on function public.get_raid_schedule() to authenticated, service_role;

create or replace function public.create_raid_room(target_event_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  player_id uuid := auth.uid();
  event public.raid_events;
  room public.raid_rooms;
  team jsonb;
  code text;
begin
  if player_id is null then
    raise exception 'Autenticação necessária' using errcode = '42501';
  end if;

  select * into event from public.raid_events
  where id = target_event_id and is_published
  for share;

  if event.id is null or now() < event.starts_at or now() >= event.ends_at then
    raise exception 'A Raid não está ativa' using errcode = '22023';
  end if;

  team := private.active_team_snapshot(player_id);
  code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));

  insert into public.raid_rooms (event_id, host_id, invite_code)
  values (event.id, player_id, code)
  returning * into room;

  insert into public.raid_participants (room_id, user_id, seat, team_snapshot)
  values (room.id, player_id, 1, team);

  return jsonb_build_object(
    'roomId', room.id,
    'eventId', room.event_id,
    'inviteCode', room.invite_code,
    'status', room.status,
    'seat', 1
  );
end;
$$;

revoke all on function public.create_raid_room(uuid) from public, anon;
grant execute on function public.create_raid_room(uuid) to authenticated, service_role;

create or replace function public.join_raid_room(target_invite_code text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  player_id uuid := auth.uid();
  room public.raid_rooms;
  event public.raid_events;
  team jsonb;
  next_seat integer;
  participant_count integer;
begin
  if player_id is null then
    raise exception 'Autenticação necessária' using errcode = '42501';
  end if;

  select * into room from public.raid_rooms
  where invite_code = upper(trim(target_invite_code))
  for update;

  if room.id is null or room.status <> 'lobby' then
    raise exception 'Sala de Raid indisponível' using errcode = 'P0002';
  end if;

  select * into event from public.raid_events where id = room.event_id;
  if event.id is null or now() < event.starts_at or now() >= event.ends_at then
    raise exception 'O evento não está ativo' using errcode = '22023';
  end if;

  if exists (
    select 1 from public.raid_participants
    where room_id = room.id and user_id = player_id
  ) then
    select seat into next_seat from public.raid_participants
    where room_id = room.id and user_id = player_id;
    return jsonb_build_object('roomId', room.id, 'seat', next_seat, 'alreadyJoined', true);
  end if;

  select count(*) into participant_count from public.raid_participants where room_id = room.id;
  if participant_count >= event.max_players then
    raise exception 'A sala está cheia' using errcode = '22023';
  end if;

  team := private.active_team_snapshot(player_id);
  select candidate into next_seat
  from generate_series(1, event.max_players) candidate
  where not exists (
    select 1 from public.raid_participants p
    where p.room_id = room.id and p.seat = candidate
  )
  order by candidate
  limit 1;

  insert into public.raid_participants (room_id, user_id, seat, team_snapshot)
  values (room.id, player_id, next_seat, team);

  return jsonb_build_object('roomId', room.id, 'seat', next_seat, 'alreadyJoined', false);
end;
$$;

revoke all on function public.join_raid_room(text) from public, anon;
grant execute on function public.join_raid_room(text) to authenticated, service_role;

create or replace function public.set_raid_ready(target_room_id uuid, ready boolean)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  player_id uuid := auth.uid();
begin
  if player_id is null then
    raise exception 'Autenticação necessária' using errcode = '42501';
  end if;
  if not private.is_raid_participant(target_room_id) then
    raise exception 'Você não participa desta sala' using errcode = '42501';
  end if;
  if not exists (select 1 from public.raid_rooms where id = target_room_id and status = 'lobby') then
    raise exception 'A sala já iniciou' using errcode = '22023';
  end if;

  update public.raid_participants
  set is_ready = ready,
      presence_status = case when ready then 'ready' else 'online' end,
      last_seen_at = now()
  where room_id = target_room_id and user_id = player_id;

  return jsonb_build_object('roomId', target_room_id, 'ready', ready);
end;
$$;

revoke all on function public.set_raid_ready(uuid, boolean) from public, anon;
grant execute on function public.set_raid_ready(uuid, boolean) to authenticated, service_role;

create or replace function public.leave_raid_room(target_room_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  player_id uuid := auth.uid();
  room public.raid_rooms;
begin
  if player_id is null then
    raise exception 'Autenticação necessária' using errcode = '42501';
  end if;
  select * into room from public.raid_rooms where id = target_room_id for update;
  if room.id is null or room.status <> 'lobby' then
    raise exception 'A sala não pode ser abandonada neste momento' using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.raid_participants
    where room_id = target_room_id and user_id = player_id
  ) then
    raise exception 'Você não participa desta sala' using errcode = '42501';
  end if;

  delete from public.raid_participants
  where room_id = target_room_id and user_id = player_id;

  if player_id = room.host_id then
    update public.raid_rooms set status = 'closed' where id = target_room_id;
  end if;

  return jsonb_build_object('roomId', target_room_id, 'left', true);
end;
$$;

revoke all on function public.leave_raid_room(uuid) from public, anon;
grant execute on function public.leave_raid_room(uuid) to authenticated, service_role;

create or replace function public.start_raid_room(
  target_room_id uuid,
  submitted_state jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  room public.raid_rooms;
  event public.raid_events;
  participant_count integer;
  ready_count integer;
begin
  select * into room from public.raid_rooms where id = target_room_id for update;
  if room.id is null or room.status <> 'lobby' then
    raise exception 'Sala indisponível' using errcode = 'P0002';
  end if;
  select * into event from public.raid_events where id = room.event_id;
  select count(*), count(*) filter (where is_ready)
  into participant_count, ready_count
  from public.raid_participants where room_id = room.id;

  if participant_count < event.min_players or participant_count > event.max_players then
    raise exception 'Quantidade de jogadores inválida' using errcode = '22023';
  end if;
  if ready_count <> participant_count then
    raise exception 'Todos os jogadores precisam estar prontos' using errcode = '22023';
  end if;
  if jsonb_typeof(submitted_state) is distinct from 'object'
    or submitted_state ->> 'version' is distinct from '1'
    or submitted_state ->> 'roomId' is distinct from target_room_id::text
    or submitted_state ->> 'eventId' is distinct from event.id::text
    or submitted_state ->> 'bossCreatureId' is distinct from event.boss_creature_id
    or submitted_state ->> 'status' is distinct from 'active' then
    raise exception 'Estado inicial de Raid inválido' using errcode = '22023';
  end if;

  update public.raid_rooms
  set status = 'active', state = submitted_state, version = 1, started_at = now()
  where id = room.id;

  insert into public.raid_room_events (room_id, sequence, event_type, payload)
  select
    room.id,
    ordinal::integer,
    coalesce(event ->> 'kind', 'raid_event'),
    event
  from jsonb_array_elements(coalesce(submitted_state -> 'log', '[]'::jsonb))
    with ordinality as entries(event, ordinal);

  return jsonb_build_object('roomId', room.id, 'state', submitted_state, 'version', 1);
end;
$$;

revoke all on function public.start_raid_room(uuid, jsonb) from public, anon, authenticated;
grant execute on function public.start_raid_room(uuid, jsonb) to service_role;

create or replace function public.commit_raid_action(
  target_room_id uuid,
  acting_user_id uuid,
  expected_version integer,
  target_client_action_id uuid,
  target_action_type text,
  action_payload jsonb,
  result_state jsonb,
  result_events jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  room public.raid_rooms;
  previous_result jsonb;
  next_version integer;
  event_sequence integer;
  committed_result jsonb;
begin
  select * into room from public.raid_rooms where id = target_room_id for update;
  if room.id is null then
    raise exception 'Sala de Raid não encontrada' using errcode = 'P0002';
  end if;

  select result into previous_result
  from public.raid_actions
  where room_id = target_room_id
    and user_id = acting_user_id
    and client_action_id = target_client_action_id;

  if previous_result is not null then
    return previous_result;
  end if;

  if room.status <> 'active' then
    raise exception 'A Raid não está ativa' using errcode = '22023';
  end if;
  if room.version <> expected_version then
    raise exception 'Versão de Raid desatualizada' using errcode = '40001';
  end if;
  if not exists (
    select 1 from public.raid_participants
    where room_id = target_room_id and user_id = acting_user_id
  ) then
    raise exception 'Jogador não participa desta Raid' using errcode = '42501';
  end if;

  if target_action_type not in (
    'attach_energy', 'draw_power', 'equip_power', 'switch',
    'attack', 'evolve', 'pass'
  )
    or jsonb_typeof(result_state) is distinct from 'object'
    or result_state ->> 'roomId' is distinct from target_room_id::text
    or result_state ->> 'version' is distinct from '1'
    or result_state ->> 'status' not in ('active', 'victory', 'defeat') then
    raise exception 'Transição de Raid inválida' using errcode = '22023';
  end if;

  next_version := room.version + 1;
  committed_result := jsonb_build_object(
    'state', result_state,
    'events', result_events,
    'version', next_version,
    'authority', 'server'
  );

  insert into public.raid_actions (
    room_id, user_id, client_action_id, action_type, payload, result
  ) values (
    target_room_id, acting_user_id, target_client_action_id,
    target_action_type, action_payload, committed_result
  );

  update public.raid_rooms
  set state = result_state,
      version = next_version,
      status = case
        when result_state ->> 'status' = 'victory' then 'victory'
        when result_state ->> 'status' = 'defeat' then 'defeat'
        else 'active'
      end,
      finished_at = case when result_state ->> 'status' in ('victory','defeat') then now() else null end
  where id = target_room_id;

  update public.raid_participants
  set contribution = coalesce((
        select participant -> 'contribution'
        from jsonb_array_elements(result_state -> 'players') participant
        where participant ->> 'id' = acting_user_id::text
        limit 1
      ), contribution),
      last_seen_at = now()
  where room_id = target_room_id and user_id = acting_user_id;

  select coalesce(max(sequence), 0) into event_sequence
  from public.raid_room_events where room_id = target_room_id;

  insert into public.raid_room_events (room_id, sequence, event_type, payload)
  select target_room_id,
         event_sequence + ordinal::integer,
         coalesce(event ->> 'kind', 'raid_event'),
         event
  from jsonb_array_elements(result_events) with ordinality entries(event, ordinal);

  return committed_result;
end;
$$;

revoke all on function public.commit_raid_action(
  uuid, uuid, integer, uuid, text, jsonb, jsonb, jsonb
) from public, anon, authenticated;
grant execute on function public.commit_raid_action(
  uuid, uuid, integer, uuid, text, jsonb, jsonb, jsonb
) to service_role;

create or replace function public.grant_raid_mythic_rewards(target_room_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  room public.raid_rooms;
  event public.raid_events;
  participant record;
  granted_count integer := 0;
begin
  select * into room from public.raid_rooms where id = target_room_id for update;
  if room.id is null or room.status <> 'victory' then
    raise exception 'A Raid ainda não foi vencida' using errcode = '22023';
  end if;
  select * into event from public.raid_events where id = room.event_id;

  for participant in
    select * from public.raid_participants where room_id = room.id
  loop
    if coalesce((participant.contribution ->> 'actions')::integer, 0) > 0 then
      insert into public.raid_reward_ledger (
        event_id, room_id, player_id, reward_id, reward_type, creature_card_id
      ) values (
        event.id, room.id, participant.user_id,
        event.slug || ':mythic', 'mythical_reward', event.boss_creature_id
      )
      on conflict (event_id, player_id, reward_type) do nothing;

      if found then
        insert into public.player_creatures (user_id, creature_id, acquired_from)
        values (participant.user_id, event.boss_creature_id, 'raid:' || event.slug);
        granted_count := granted_count + 1;
      end if;
    end if;
  end loop;

  return jsonb_build_object('grantedCount', granted_count, 'creatureCardId', event.boss_creature_id);
end;
$$;

revoke all on function public.grant_raid_mythic_rewards(uuid) from public, anon, authenticated;
grant execute on function public.grant_raid_mythic_rewards(uuid) to service_role;

insert into public.raid_events (
  slug, title, boss_creature_id, starts_at, ends_at, presentation_timezone,
  min_players, max_players, recommended_level, boss_config, rewards, is_published
) values (
  'raid-roc-2026-10-03',
  'Roc — O Céu Desaparece',
  'roc',
  '2026-10-03T13:00:00Z',
  '2026-10-04T05:00:00Z',
  'America/Sao_Paulo',
  2,
  5,
  30,
  '{
    "maxHp":10000,
    "speed":62,
    "maxRounds":30,
    "phases":[
      {"phase":1,"minHpRatio":0.70,"name":"Asas Sobre o Horizonte"},
      {"phase":2,"minHpRatio":0.35,"name":"O Sol Desaparece","terrain":"storm"},
      {"phase":3,"minHpRatio":0.00,"name":"Tempestade do Roc","enraged":true}
    ],
    "attacks":[
      {"id":"talon-sweep","name":"Varredura de Garras","target":"single","damage":42},
      {"id":"sun-shadow","name":"Sombra do Sol","target":"all","damage":24},
      {"id":"horizon-storm","name":"Tempestade do Horizonte","target":"all","damage":34,"phase":3}
    ]
  }'::jsonb,
  '{"mythicalCreatureId":"roc","guaranteedCopies":1,"limitPerAccountPerEvent":1}'::jsonb,
  true
)
on conflict (slug) do update
set title = excluded.title,
    boss_creature_id = excluded.boss_creature_id,
    starts_at = excluded.starts_at,
    ends_at = excluded.ends_at,
    boss_config = excluded.boss_config,
    rewards = excluded.rewards,
    is_published = excluded.is_published;

create policy "raid players receive private broadcasts"
on realtime.messages for select to authenticated
using (
  exists (
    select 1
    from public.raid_participants participant
    where participant.user_id = auth.uid()
      and topic = 'raid:room:' || participant.room_id::text
  )
);


create or replace function private.broadcast_raid_room()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform realtime.broadcast_changes(
    'raid:room:' || new.id::text,
    tg_op, tg_op, tg_table_name, tg_table_schema, new, old
  );
  return new;
end;
$$;

create or replace function private.broadcast_raid_participant()
returns trigger
language plpgsql
security definer
set search_path = ''
as $
declare
  target_room_id uuid;
begin
  if tg_op = 'DELETE' then
    target_room_id := old.room_id;
  else
    target_room_id := new.room_id;
  end if;

  perform realtime.broadcast_changes(
    'raid:room:' || target_room_id::text,
    tg_op, tg_op, tg_table_name, tg_table_schema, new, old
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$;

create or replace function private.broadcast_raid_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform realtime.broadcast_changes(
    'raid:room:' || new.room_id::text,
    tg_op, tg_op, tg_table_name, tg_table_schema, new, old
  );
  return new;
end;
$$;

create trigger raid_rooms_broadcast_changes
after update on public.raid_rooms
for each row execute function private.broadcast_raid_room();

create trigger raid_participants_broadcast_changes
after insert or update or delete on public.raid_participants
for each row execute function private.broadcast_raid_participant();

create trigger raid_room_events_broadcast_changes
after insert on public.raid_room_events
for each row execute function private.broadcast_raid_event();
